// ============================================================
// sttData.ts — DigiDouble Research Portal
// Données centralisées STT / ASR (Speech-to-Text) 2025–2026
// Sources : Artificial Analysis, benchmarks officiels, docs
// ============================================================

export type STTCategory = "cloud-api" | "open-source";

export interface STTScore {
  accuracy: number;       // 1–10 (WER normalisé)
  latency: number;        // 1–10 (10 = <50ms streaming, 1 = >1s)
  multilingual: number;   // 1–10
  sovereignty: number;    // 1–10 (10 = full self-hosted)
  pricing: number;        // 1–10 (10 = gratuit)
  streaming: number;      // 1–10 (support streaming temps réel)
}

export interface STTData {
  id: string;
  name: string;
  category: STTCategory;
  tagline: string;
  homepageUrl: string;
  docsUrl: string;
  // Specs techniques
  wer: number;              // Word Error Rate % (lower = better), 0 if N/A
  werNote: string;
  latencyMs: number;        // Latence streaming (TTFA ou P90) en ms
  latencyMsTypical: number;
  architecture: string;
  params: string;
  license: string;
  selfHostable: boolean;
  selfHostNote: string;
  // Pricing
  pricePerHour: number;     // $ par heure d'audio
  pricePerMin: number;
  priceNote: string;
  freeTier: string;
  // Capacités
  streaming: boolean;
  streamingDetail: string;
  multilingual: boolean;
  languages: number;
  speakerDiarization: boolean;
  wordTimestamps: boolean;
  punctuation: boolean;
  customVocabulary: boolean;
  // Souveraineté
  onPremise: boolean;
  onPremiseDetail: string;
  gdprCompliant: boolean;
  dataResidency: string;
  // Scores
  score: STTScore;
  // Description
  description: string;
  descriptionFr: string;
  strengths: string[];
  strengthsFr: string[];
  weaknesses: string[];
  weaknessesFr: string[];
  // Pertinence DigiDouble
  digiDoubleRelevance: string;
  digiDoubleRelevanceFr: string;
  digiDoubleAxis: string;
  benchmarkRef?: string;
  // Traçabilité des données
  dataUpdatedAt: string;      // ISO date de la dernière mise à jour des chiffres (YYYY-MM-DD)
  dataUpdateNote: string;     // Contexte de la mise à jour
  sources: Array<{ label: string; url: string; type: "pricing" | "benchmark" | "docs" | "news" }>;
  // Voice Agent API (pipeline complet STT+LLM+TTS)
  voiceAgentApi?: {
    available: boolean;
    price?: string;       // ex: "$4.50/hr"
    note?: string;        // ex: "WebSocket STT+LLM+TTS unifié"
    url?: string;
  };
}

const sttDatabase: STTData[] = [
  // ─── CLOUD API ───────────────────────────────────────────────
  {
    id: "deepgram-nova3",
    name: "Deepgram Nova-3",
    category: "cloud-api",
    tagline: "Fastest streaming ASR — 75ms, 36 languages, Voice Agent API $4.50/hr, on-premise option",
    homepageUrl: "https://deepgram.com",
    docsUrl: "https://developers.deepgram.com",
    wer: 7.2,
    werNote: "7.2% WER on English (Koenecke benchmark). 12–18% on noisy/accented speech.",
    latencyMs: 75,
    latencyMsTypical: 200,
    architecture: "End-to-end deep learning (proprietary), streaming-native",
    params: "N/A (cloud)",
    license: "Commercial",
    selfHostable: true,
    selfHostNote: "On-premise deployment available (enterprise). Self-hosted via Docker.",
    pricePerHour: 0.216,
    pricePerMin: 0.0036,
    priceNote: "$0.0036/min (Pay-as-you-go). $0.0024/min (Growth plan). On-premise: custom pricing.",
    freeTier: "$200 credit on signup",
    streaming: true,
    streamingDetail: "WebSocket streaming. 75ms P90 latency. Interim results with endpointing. Voice Activity Detection (VAD) built-in.",
    multilingual: true,
    languages: 36,
    speakerDiarization: true,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: true,
    onPremise: true,
    onPremiseDetail: "Self-hosted Docker deployment. Enterprise on-premise available. Partial sovereignty.",
    gdprCompliant: true,
    dataResidency: "US (default). EU data residency available.",
    score: { accuracy: 8, latency: 10, multilingual: 7, sovereignty: 5, pricing: 7, streaming: 10 },
    description: "Deepgram Nova-3 is the industry reference for real-time voice agent ASR. 75ms P90 streaming latency, 36 languages, built-in VAD and endpointing. Voice Agent API at $4.50/hr provides a complete STT+LLM+TTS pipeline in a single WebSocket, with BYO LLM (GPT-4, Claude, Gemini) and function calling for RAG integration. No native voice cloning — Aura-2 TTS offers 36 preset voices; external TTS (ElevenLabs, Cartesia) can be integrated. On-premise deployment available for Enterprise (partial sovereignty). EU endpoint available. Used by Tavus, Simli, and most commercial avatar platforms.",
    descriptionFr: "Deepgram Nova-3 est la référence industrie pour l'ASR d'agents vocaux temps réel. 75ms P90 en streaming, 36 langues, VAD et endpointing intégrés. Voice Agent API à 4,50$/h : pipeline complet STT+LLM+TTS en 1 WebSocket, BYO LLM (GPT-4, Claude, Gemini) et function calling pour intégration RAG. Pas de clonage vocal natif — Aura-2 TTS propose 36 voix prédéfinies ; TTS externe (ElevenLabs, Cartesia) intégrable. Déploiement on-premise disponible en Enterprise. Endpoint EU disponible. Utilisé par Tavus, Simli et la plupart des plateformes d'avatars commerciales.",
    strengths: ["75ms P90 streaming latency", "Voice Agent API $4.50/hr — BYO LLM + function calling", "Built-in VAD + endpointing", "36 languages", "On-premise Enterprise option", "EU endpoint available", "LiveKit/Pipecat native integration", "Speaker diarization + word timestamps"],
    strengthsFr: ["75ms P90 latence streaming", "Voice Agent API 4,50$/h — BYO LLM + function calling", "VAD + endpointing intégrés", "36 langues", "Option on-premise Enterprise", "Endpoint EU disponible", "Intégration native LiveKit/Pipecat", "Diarisation + timestamps mot-à-mot"],
    weaknesses: ["Cloud-first (sovereignty limited — on-premise Enterprise only)", "7.2% WER on English (not best-in-class)", "French/German WER higher (~15%)", "No native voice cloning — Aura-2 preset voices only", "No native RAG — requires external function calling infrastructure", "No open-weights"],
    weaknessesFr: ["Cloud-first (souveraineté limitée — on-premise Enterprise uniquement)", "7,2% WER en anglais (pas le meilleur)", "WER français/allemand plus élevé (~15%)", "Pas de clonage vocal natif — voix Aura-2 prédéfinies uniquement", "Pas de RAG natif — function calling + infrastructure externe requis", "Pas d'open-weights"],
    digiDoubleRelevance: "Primary candidate for Phase 1 MVP ASR. 75ms latency is critical for sub-2s pipeline. On-premise option aligns with Swiss sovereignty requirements. Audiogami (Gamilab) already in production — Deepgram as fallback/comparison.",
    digiDoubleRelevanceFr: "Candidat principal pour l'ASR du MVP Phase 1. 75ms latence critique pour le pipeline <2s. Option on-premise alignée avec les exigences de souveraineté suisse. Audiogami (Gamilab) déjà en production — Deepgram comme fallback/comparaison.",
    digiDoubleAxis: "Phase 1 MVP — ASR streaming",
    benchmarkRef: "Inworld benchmark 2026 + Koenecke et al.",
    voiceAgentApi: {
      available: true,
      price: "$4.50/hr",
      note: "Deepgram Voice Agent API : pipeline complet STT (Nova-3) + LLM (BYO ou Deepgram) + TTS (Aura-2) en 1 WebSocket. Function calling natif. Barge-in + turn detection. BYO LLM (GPT-4, Claude, Gemini) → payer seulement les composants audio. Déploiement EU disponible (wss://api.eu.deepgram.com). On-premise Voice Agent en Enterprise.",
      url: "https://developers.deepgram.com/docs/voice-agent",
    },
    dataUpdatedAt: "2026-05-02",
    dataUpdateNote: "Voice Agent API $4.50/hr confirmé (mai 2026). Nova-3 TTFA 75ms P90 confirmé. Pricing PAYG: $0.0036/min STT. BYO LLM disponible. On-premise Enterprise. EU endpoint disponible. Clonage vocal : NON natif — Aura-2 TTS 36 voix prédéfinies, intégration TTS externe possible (ElevenLabs, Cartesia). RAG : via function calling JSON Schema (pas de RAG natif).",
    sources: [
      { label: "Deepgram Pricing (mai 2026)", url: "https://deepgram.com/pricing", type: "pricing" },
      { label: "Deepgram Voice Agent API Docs", url: "https://developers.deepgram.com/docs/voice-agent", type: "docs" },
      { label: "Deepgram Nova-3 Models", url: "https://developers.deepgram.com/docs/models-languages-overview", type: "docs" },
      { label: "Artificial Analysis STT Benchmark", url: "https://artificialanalysis.ai/speech-to-text", type: "benchmark" },
      { label: "Inworld STT Benchmark 2026", url: "https://inworld.ai/resources/best-speech-to-text-apis", type: "benchmark" },
      { label: "Deepgram Self-Hosted Docs", url: "https://developers.deepgram.com/docs/self-hosted", type: "docs" },
    ],
  },
  {
    id: "assemblyai",
    name: "AssemblyAI Universal-3 Pro",
    category: "cloud-api",
    tagline: "Voice Agent API — pipeline STT+LLM+TTS complet, $4.50/hr, Universal-3 Pro Streaming",
    homepageUrl: "https://www.assemblyai.com",
    docsUrl: "https://www.assemblyai.com/docs/voice-agents/voice-agent-api",
    wer: 4.9,
    werNote: "Universal-2: 4.9% WER (best-in-class cloud). Universal-3 Pro: précision supérieure sur rare words, alphanumériques, speech bruité. Universal-3 Pro Streaming: optimisé temps réel <10s utterances.",
    latencyMs: 150,
    latencyMsTypical: 300,
    architecture: "Universal-3 Pro (prompt-based transformer, domain customization sans retraining). Universal-3 Pro Streaming (u3-rt-pro) pour voice agents temps réel. Voice Agent API = WebSocket unique STT+LLM+TTS.",
    params: "N/A (cloud)",
    license: "Commercial",
    selfHostable: false,
    selfHostNote: "Cloud only. No on-premise option. EU data residency available.",
    pricePerHour: 0.372,
    pricePerMin: 0.0062,
    priceNote: "STT async: $0.21/hr (Universal-3 Pro) ou $0.15/hr (Universal-2). STT streaming: $0.0062/min. Voice Agent API (pipeline complet STT+LLM+TTS): $4.50/hr flat. $50 crédit gratuit au signup.",
    freeTier: "$50 credit on signup — no credit card required",
    streaming: true,
    streamingDetail: "Universal-3 Pro Streaming (u3-rt-pro): WebSocket temps réel, turn detection sémantique + acoustique, barge-in natif, session resumption 30s, live config update mid-conversation.",
    multilingual: true,
    languages: 99,
    speakerDiarization: true,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: true,
    onPremise: false,
    onPremiseDetail: "Cloud only. No on-premise. EU data residency available (GDPR, SOC 2 Type 2, ISO 27001, HIPAA, PCI DSS).",
    gdprCompliant: true,
    dataResidency: "US (default). EU data residency disponible. SOC 2 Type 2, ISO 27001, HIPAA, PCI DSS.",
    score: { accuracy: 10, latency: 7, multilingual: 10, sovereignty: 1, pricing: 5, streaming: 9 },
    description: "AssemblyAI a lancé sa Voice Agent API le 29 avril 2026 : pipeline complet STT+LLM+TTS en une seule connexion WebSocket à $4.50/hr flat. Universal-3 Pro Streaming (u3-rt-pro) est le modèle STT temps réel, avec turn detection sémantique+acoustique, barge-in natif et session resumption. Tool calling (JSON Schema) permet d'intégrer un RAG custom (Pinecone, LlamaIndex, etc.) via function calling — pas de RAG natif mais intégration externe complète. Pas de clonage vocal natif : les voix disponibles sont prédéfinies (18+ voix EN/multilingual), mais il est possible d'intégrer un TTS externe (ElevenLabs, Cartesia) pour un clone vocal custom. LeMUR AI features (summarization, Q&A, sentiment) disponibles sur transcriptions. 99 langues, diarisation, timestamps mot-à-mot.",
    descriptionFr: "AssemblyAI a lancé sa Voice Agent API le 29 avril 2026 : pipeline complet STT+LLM+TTS en une seule connexion WebSocket à 4,50$/h forfait. Universal-3 Pro Streaming est le modèle STT temps réel avec détection de tour sémantique+acoustique, barge-in natif et reprise de session. Le tool calling (JSON Schema) permet d'intégrer un RAG custom (Pinecone, LlamaIndex, etc.) via function calling — pas de RAG natif mais intégration externe complète. Pas de clonage vocal natif : les voix sont prédéfinies (18+ voix EN/multilingue), mais il est possible d'intégrer un TTS externe (ElevenLabs, Cartesia) pour un clone vocal custom. Fonctionnalités LeMUR (résumé, Q&R, sentiment) disponibles sur les transcriptions.",
    strengths: [
      "Voice Agent API : pipeline STT+LLM+TTS complet en 1 WebSocket, $4.50/hr flat",
      "Universal-3 Pro Streaming : turn detection sémantique+acoustique, barge-in natif",
      "Tool calling JSON Schema → RAG custom intégrable (Pinecone, LlamaIndex, etc.)",
      "Session resumption 30s, live config update mid-conversation",
      "4.9% WER Universal-2 — meilleure précision cloud",
      "99 langues, diarisation, LeMUR AI (résumé, Q&R, sentiment)",
      "GDPR, SOC 2 Type 2, ISO 27001, HIPAA, PCI DSS",
    ],
    strengthsFr: [
      "Voice Agent API : pipeline complet en 1 WebSocket, 4,50$/h forfait",
      "Universal-3 Pro Streaming : détection de tour sémantique+acoustique, barge-in natif",
      "Tool calling → RAG custom intégrable (Pinecone, LlamaIndex, etc.)",
      "Reprise de session 30s, mise à jour config en direct mid-conversation",
      "4,9% WER Universal-2 — meilleure précision cloud",
      "99 langues, diarisation, LeMUR AI (résumé, Q&R, sentiment)",
      "GDPR, SOC 2 Type 2, ISO 27001, HIPAA, PCI DSS",
    ],
    weaknesses: [
      "Pas de clonage vocal natif — voix prédéfinies uniquement (TTS externe possible via intégration)",
      "Pas de RAG natif — nécessite tool calling + infrastructure RAG externe",
      "Cloud only — pas d'option on-premise, souveraineté limitée",
      "Voice Agent API : LLM intégré non personnalisable nativement (custom LLM via Retell AI possible)",
      "$4.50/hr Voice Agent API — coût élevé pour usage intensif",
    ],
    weaknessesFr: [
      "Pas de clonage vocal natif — voix prédéfinies (TTS externe intégrable)",
      "Pas de RAG natif — tool calling + infrastructure RAG externe requis",
      "Cloud uniquement — pas d'option on-premise",
      "LLM du Voice Agent API non personnalisable nativement",
      "4,50$/h Voice Agent API — coût élevé pour usage intensif",
    ],
    digiDoubleRelevance: "Voice Agent API très pertinent pour DigiDouble Phase 1 : pipeline STT+LLM+TTS en 1 WebSocket simplifie l'architecture. Tool calling permet d'intégrer un RAG sur la base de connaissances DigiDouble. Pas de clonage vocal natif : intégrer ElevenLabs ou Cartesia via TTS externe pour la voix du DigiDouble. Référence précision WER pour benchmarking.",
    digiDoubleRelevanceFr: "Voice Agent API très pertinent pour DigiDouble Phase 1 : pipeline complet en 1 WebSocket simplifie l'architecture. Tool calling permet d'intégrer un RAG sur la base de connaissances DigiDouble. Pas de clonage vocal natif : intégrer ElevenLabs ou Cartesia via TTS externe. Référence précision WER pour benchmarking.",
    digiDoubleAxis: "Voice Agent Pipeline — Référence précision",
    benchmarkRef: "AssemblyAI Voice Agent API launch (Apr 29, 2026) + pricing page",
    voiceAgentApi: {
      available: true,
      price: "$4.50/hr",
      note: "Pipeline complet STT+LLM+TTS en 1 WebSocket. Turn detection sémantique+acoustique, barge-in natif, tool calling JSON Schema. Lancé le 29 avr. 2026.",
      url: "https://www.assemblyai.com/products/voice-agent-api",
    },
    dataUpdatedAt: "2026-05-01",
    dataUpdateNote: "Mise à jour majeure : lancement Voice Agent API le 29 avril 2026. Universal-3 Pro Streaming (u3-rt-pro) nouveau modèle STT temps réel. Prix Voice Agent API : $4.50/hr flat (STT+LLM+TTS). STT seul : $0.21/hr Universal-3 Pro, $0.15/hr Universal-2. Clonage vocal : NON natif (voix prédéfinies, TTS externe intégrable). RAG : NON natif mais tool calling JSON Schema permet intégration externe complète.",
    sources: [
      { label: "AssemblyAI Voice Agent API — Lancement (29 avr. 2026)", url: "https://www.assemblyai.com/blog/introducing-our-voice-agent-api", type: "news" },
      { label: "AssemblyAI Voice Agent API — Produit", url: "https://www.assemblyai.com/products/voice-agent-api", type: "docs" },
      { label: "AssemblyAI Voice Agent API — Documentation", url: "https://www.assemblyai.com/docs/voice-agents/voice-agent-api", type: "docs" },
      { label: "AssemblyAI Pricing (Voice Agent $4.50/hr)", url: "https://www.assemblyai.com/pricing", type: "pricing" },
      { label: "Universal-3 Pro Streaming", url: "https://www.assemblyai.com/universal-3-pro-streaming", type: "docs" },
      { label: "AssemblyAI Benchmarks", url: "https://www.assemblyai.com/benchmarks", type: "benchmark" },
      { label: "Artificial Analysis STT", url: "https://artificialanalysis.ai/speech-to-text", type: "benchmark" },
    ],
  },
  {
    id: "google-stt",
    name: "Google Speech-to-Text v2",
    category: "cloud-api",
    tagline: "Chirp 2 model — 125 languages, streaming, Google ecosystem",
    homepageUrl: "https://cloud.google.com/speech-to-text",
    docsUrl: "https://cloud.google.com/speech-to-text/docs",
    wer: 6.8,
    werNote: "6.8% WER English (Chirp 2). Competitive on multilingual.",
    latencyMs: 200,
    latencyMsTypical: 400,
    architecture: "Chirp 2 (USM — Universal Speech Model, 2B params)",
    params: "2B (USM)",
    license: "Commercial",
    selfHostable: false,
    selfHostNote: "Cloud only (GCP). No on-premise.",
    pricePerHour: 0.36,
    pricePerMin: 0.006,
    priceNote: "$0.006/min (Chirp 2). $0.004/min (standard). Free: 60 min/month.",
    freeTier: "60 minutes/month",
    streaming: true,
    streamingDetail: "Bidirectional streaming gRPC. 200ms typical latency. Interim results available.",
    multilingual: true,
    languages: 125,
    speakerDiarization: true,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: true,
    onPremise: false,
    onPremiseDetail: "GCP cloud only.",
    gdprCompliant: true,
    dataResidency: "EU region available (Belgium, Netherlands).",
    score: { accuracy: 8, latency: 6, multilingual: 10, sovereignty: 2, pricing: 6, streaming: 7 },
    description: "Google STT v2 with Chirp 2 (USM 2B) covers 125 languages with competitive accuracy. gRPC bidirectional streaming. Deep integration with Google ecosystem (Dialogflow, Vertex AI). 200ms typical streaming latency. EU data residency available. No on-premise option.",
    descriptionFr: "Google STT v2 avec Chirp 2 (USM 2B) couvre 125 langues avec une précision compétitive. Streaming bidirectionnel gRPC. Intégration profonde avec l'écosystème Google (Dialogflow, Vertex AI). 200ms de latence streaming typique. Résidence données EU disponible. Pas d'option on-premise.",
    strengths: ["125 languages — widest coverage", "Chirp 2 (USM 2B) quality", "EU data residency available", "gRPC streaming", "Google ecosystem integration"],
    strengthsFr: ["125 langues — couverture la plus large", "Chirp 2 (USM 2B) qualité", "Résidence données EU disponible", "Streaming gRPC", "Intégration écosystème Google"],
    weaknesses: ["200ms latency (2.7× Deepgram)", "Cloud only, no sovereignty", "Complex pricing tiers", "No open-weights"],
    weaknessesFr: ["200ms latence (2,7× Deepgram)", "Cloud uniquement, pas de souveraineté", "Tarification complexe", "Pas d'open-weights"],
    digiDoubleRelevance: "Useful for multilingual DigiDouble deployments requiring 100+ language support. EU data residency partially addresses Swiss sovereignty. Not recommended for Phase 1 MVP due to higher latency than Deepgram.",
    digiDoubleRelevanceFr: "Utile pour les déploiements DigiDouble multilingues nécessitant 100+ langues. Résidence données EU adresse partiellement la souveraineté suisse. Non recommandé pour le MVP Phase 1 en raison d'une latence plus élevée que Deepgram.",
    digiDoubleAxis: "Multilingue — option secondaire",
    benchmarkRef: "Google Cloud docs + Koenecke benchmark 2025",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Chirp 3 public preview (Nov 2025). Pricing: $0.016/min (0-500k min). WER ~4-6% on Chirp 3 (Google internal). 85+ languages with Chirp 3.",
    sources: [
      { label: "Google STT Pricing", url: "https://cloud.google.com/speech-to-text/pricing", type: "pricing" },
      { label: "Google Chirp 3 Announcement", url: "https://cloud.google.com/blog/products/ai-machine-learning/google-cloud-chirp-3-speech-to-text", type: "news" },
      { label: "Google STT Docs", url: "https://cloud.google.com/speech-to-text/docs", type: "docs" },
      { label: "Artificial Analysis STT", url: "https://artificialanalysis.ai/speech-to-text", type: "benchmark" },
    ],
  },
  {
    id: "azure-stt",
    name: "Azure Speech (Microsoft)",
    category: "cloud-api",
    tagline: "Enterprise-grade STT — 100+ languages, custom models, EU sovereign",
    homepageUrl: "https://azure.microsoft.com/en-us/products/ai-services/speech-to-text",
    docsUrl: "https://learn.microsoft.com/en-us/azure/ai-services/speech-service/",
    wer: 5.9,
    werNote: "5.9% WER English. Strong on Swiss German with custom model.",
    latencyMs: 180,
    latencyMsTypical: 350,
    architecture: "Custom Neural Voice + Universal model (proprietary)",
    params: "N/A (cloud)",
    license: "Commercial",
    selfHostable: true,
    selfHostNote: "Azure Stack / disconnected containers available. Partial on-premise.",
    pricePerHour: 1.00,
    pricePerMin: 0.0167,
    priceNote: "$1.00/hour standard. $1.50/hour custom model. Commitment tiers available.",
    freeTier: "5 hours/month free",
    streaming: true,
    streamingDetail: "WebSocket + REST streaming. 180ms typical latency. Continuous recognition mode.",
    multilingual: true,
    languages: 100,
    speakerDiarization: true,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: true,
    onPremise: true,
    onPremiseDetail: "Azure Stack + disconnected containers. Swiss data center available (Zurich).",
    gdprCompliant: true,
    dataResidency: "EU (Switzerland North — Zurich available).",
    score: { accuracy: 9, latency: 7, multilingual: 9, sovereignty: 6, pricing: 3, streaming: 8 },
    description: "Azure Speech offers enterprise-grade STT with 100+ languages, custom model training, and Swiss data center (Zurich). 5.9% WER on English. Disconnected container deployment for partial sovereignty. Most expensive option but strongest enterprise compliance. Swiss German custom model available.",
    descriptionFr: "Azure Speech offre un STT enterprise avec 100+ langues, entraînement de modèles personnalisés et datacenter suisse (Zurich). 5,9% WER en anglais. Déploiement en conteneur déconnecté pour une souveraineté partielle. Option la plus chère mais la plus forte en conformité enterprise. Modèle personnalisé suisse-allemand disponible.",
    strengths: ["Swiss data center (Zurich)", "Custom model training", "5.9% WER accuracy", "Disconnected container deployment", "Swiss German support"],
    strengthsFr: ["Datacenter suisse (Zurich)", "Entraînement modèle personnalisé", "5,9% WER précision", "Déploiement conteneur déconnecté", "Support suisse-allemand"],
    weaknesses: ["Most expensive ($1/hour)", "180ms latency", "Complex setup for on-premise", "Microsoft ecosystem dependency"],
    weaknessesFr: ["Plus cher ($1/heure)", "180ms latence", "Configuration complexe on-premise", "Dépendance écosystème Microsoft"],
    digiDoubleRelevance: "Strong candidate for Swiss institutional deployments requiring data residency in Switzerland. Swiss German custom model critical for DigiDouble Swiss market. Too expensive for high-volume production.",
    digiDoubleRelevanceFr: "Candidat fort pour les déploiements institutionnels suisses nécessitant la résidence des données en Suisse. Modèle suisse-allemand critique pour le marché suisse DigiDouble. Trop cher pour la production à volume élevé.",
    digiDoubleAxis: "Souveraineté suisse — institutionnel",
    benchmarkRef: "Microsoft docs + Azure pricing 2026",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Azure pricing updated Apr 2026: $1/hr standard, $0.18/hr batch. WER 4.3% (Microsoft internal). Swiss data center (Switzerland North) confirmed. Disconnected container deployment available.",
    sources: [
      { label: "Azure Speech Pricing", url: "https://azure.microsoft.com/en-us/pricing/details/cognitive-services/speech-services/", type: "pricing" },
      { label: "Azure Speech Docs", url: "https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-to-text", type: "docs" },
      { label: "Azure Switzerland North", url: "https://azure.microsoft.com/en-us/explore/global-infrastructure/geographies/#geography=switzerland", type: "docs" },
      { label: "Artificial Analysis STT", url: "https://artificialanalysis.ai/speech-to-text/models/azure", type: "benchmark" },
    ],
  },
  // ─── OPEN SOURCE ─────────────────────────────────────────────
  {
    id: "whisper-large-v3",
    name: "Whisper Large v3 (OpenAI)",
    category: "open-source",
    tagline: "Open-source reference — 99 languages, 2.7% WER, self-hostable",
    homepageUrl: "https://github.com/openai/whisper",
    docsUrl: "https://platform.openai.com/docs/guides/speech-to-text",
    wer: 2.7,
    werNote: "2.7% WER English (LibriSpeech clean). Best open-source accuracy. 8–15% on noisy/accented.",
    latencyMs: 300,
    latencyMsTypical: 800,
    architecture: "Encoder-decoder Transformer (1.5B params)",
    params: "1.5B",
    license: "MIT",
    selfHostable: true,
    selfHostNote: "Full self-hosted. GPU recommended (A100 for real-time). CPU possible with quantization.",
    pricePerHour: 0,
    pricePerMin: 0,
    priceNote: "Free (self-hosted). OpenAI API: $0.006/min. GPU compute cost: ~$0.10–0.50/hour.",
    freeTier: "Fully free (self-hosted)",
    streaming: false,
    streamingDetail: "Batch processing only. Not streaming-native. Use faster-whisper or whisper-streaming for near-real-time.",
    multilingual: true,
    languages: 99,
    speakerDiarization: false,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: false,
    onPremise: true,
    onPremiseDetail: "Full on-premise. MIT license. Complete sovereignty.",
    gdprCompliant: true,
    dataResidency: "Full control — data never leaves your infrastructure.",
    score: { accuracy: 10, latency: 4, multilingual: 10, sovereignty: 10, pricing: 10, streaming: 3 },
    description: "Whisper Large v3 is the open-source ASR reference with 2.7% WER on English (best open-source). MIT license, 99 languages, full self-hosting. Not streaming-native — requires faster-whisper or whisper-streaming for real-time use. Audiogami (Gamilab) is based on Whisper with Swiss-specific optimizations.",
    descriptionFr: "Whisper Large v3 est la référence ASR open-source avec 2,7% WER en anglais (meilleur open-source). Licence MIT, 99 langues, self-hosting complet. Pas streaming-natif — nécessite faster-whisper ou whisper-streaming pour l'usage temps réel. Audiogami (Gamilab) est basé sur Whisper avec des optimisations spécifiques suisses.",
    strengths: ["2.7% WER — best open-source accuracy", "MIT license — full sovereignty", "99 languages", "Free (self-hosted)", "Audiogami (Gamilab) production-ready variant"],
    strengthsFr: ["2,7% WER — meilleure précision open-source", "Licence MIT — souveraineté totale", "99 langues", "Gratuit (self-hosted)", "Audiogami (Gamilab) variante production"],
    weaknesses: ["Not streaming-native (batch)", "300ms+ latency for real-time use", "GPU required for production speed", "No speaker diarization"],
    weaknessesFr: ["Pas streaming-natif (batch)", "300ms+ latence pour usage temps réel", "GPU requis pour vitesse production", "Pas de diarisation"],
    digiDoubleRelevance: "Foundation of Audiogami (Gamilab) — already in production for DigiDouble. Use faster-whisper with VAD for Phase 1 streaming pipeline. Full sovereignty aligns with Swiss requirements. Benchmark against Deepgram Nova-3 for latency trade-off.",
    digiDoubleRelevanceFr: "Fondation d'Audiogami (Gamilab) — déjà en production pour DigiDouble. Utiliser faster-whisper avec VAD pour le pipeline streaming Phase 1. Souveraineté totale alignée avec les exigences suisses. Benchmarker contre Deepgram Nova-3 pour le compromis latence.",
    digiDoubleAxis: "Phase 1 MVP — Base Audiogami",
    benchmarkRef: "OpenAI Whisper paper + Koenecke benchmark 2025",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Whisper Large v3 released Sep 2023. WER 2.7% on LibriSpeech clean (OpenAI). OpenAI API pricing: $0.006/min. Groq inference: $0.35/1M tokens (sub-100ms). Model unchanged since release.",
    sources: [
      { label: "Whisper GitHub", url: "https://github.com/openai/whisper", type: "docs" },
      { label: "OpenAI Whisper API Pricing", url: "https://openai.com/api/pricing/", type: "pricing" },
      { label: "Groq Whisper Pricing", url: "https://groq.com/pricing/", type: "pricing" },
      { label: "HuggingFace Open ASR Leaderboard", url: "https://huggingface.co/spaces/hf-audio/open_asr_leaderboard", type: "benchmark" },
    ],
  },
  {
    id: "faster-whisper",
    name: "faster-whisper (CTranslate2)",
    category: "open-source",
    tagline: "4× faster Whisper inference — streaming-capable, CPU/GPU, production-ready",
    homepageUrl: "https://github.com/SYSTRAN/faster-whisper",
    docsUrl: "https://github.com/SYSTRAN/faster-whisper",
    wer: 2.7,
    werNote: "Same accuracy as Whisper Large v3 (identical weights, optimized inference).",
    latencyMs: 150,
    latencyMsTypical: 300,
    architecture: "CTranslate2 optimized Whisper (int8 quantization, beam search)",
    params: "1.5B (same as Whisper Large v3)",
    license: "MIT",
    selfHostable: true,
    selfHostNote: "Full self-hosted. 4× faster than original Whisper. CPU viable with int8 quantization.",
    pricePerHour: 0,
    pricePerMin: 0,
    priceNote: "Free (self-hosted). GPU compute: ~$0.05–0.20/hour with int8.",
    freeTier: "Fully free",
    streaming: true,
    streamingDetail: "Streaming mode with VAD (silero-vad). 150ms latency with chunked processing. Used in whisper-streaming and LiveKit integrations.",
    multilingual: true,
    languages: 99,
    speakerDiarization: false,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: false,
    onPremise: true,
    onPremiseDetail: "Full on-premise. MIT license.",
    gdprCompliant: true,
    dataResidency: "Full control.",
    score: { accuracy: 10, latency: 7, multilingual: 10, sovereignty: 10, pricing: 10, streaming: 7 },
    description: "faster-whisper is the production-ready variant of Whisper using CTranslate2 for 4× faster inference with the same accuracy. int8 quantization enables CPU deployment. Streaming mode with silero-vad achieves 150ms latency. Used in LiveKit voice agent templates and Audiogami-style deployments.",
    descriptionFr: "faster-whisper est la variante production de Whisper utilisant CTranslate2 pour une inférence 4× plus rapide avec la même précision. La quantification int8 permet le déploiement CPU. Le mode streaming avec silero-vad atteint 150ms de latence. Utilisé dans les templates d'agents vocaux LiveKit.",
    strengths: ["4× faster than original Whisper", "Same 2.7% WER accuracy", "CPU viable with int8", "Streaming mode with VAD", "MIT license — full sovereignty", "LiveKit integration available"],
    strengthsFr: ["4× plus rapide que Whisper original", "Même précision 2,7% WER", "CPU viable avec int8", "Mode streaming avec VAD", "Licence MIT — souveraineté totale", "Intégration LiveKit disponible"],
    weaknesses: ["150ms latency (2× Deepgram)", "No speaker diarization", "Requires VAD setup for streaming", "GPU still recommended for production"],
    weaknessesFr: ["150ms latence (2× Deepgram)", "Pas de diarisation", "Configuration VAD requise pour streaming", "GPU toujours recommandé en production"],
    digiDoubleRelevance: "Recommended for Phase 1 MVP sovereign ASR pipeline. 4× faster than base Whisper, streaming-capable with VAD. Combine with silero-vad for real-time endpointing. Full sovereignty. Benchmark: 150ms vs Deepgram 75ms — acceptable trade-off for Swiss sovereign deployment.",
    digiDoubleRelevanceFr: "Recommandé pour le pipeline ASR souverain du MVP Phase 1. 4× plus rapide que Whisper de base, streaming avec VAD. Combiner avec silero-vad pour l'endpointing temps réel. Souveraineté totale. Benchmark : 150ms vs Deepgram 75ms — compromis acceptable pour déploiement souverain suisse.",
    digiDoubleAxis: "Phase 1 MVP — ASR souverain",
    benchmarkRef: "SYSTRAN faster-whisper benchmarks 2025",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "faster-whisper v1.1.0 (Jan 2025). 4× faster than original Whisper on GPU, 2× on CPU with int8. Streaming mode with silero-vad confirmed. LiveKit voice agent template uses faster-whisper.",
    sources: [
      { label: "faster-whisper GitHub", url: "https://github.com/SYSTRAN/faster-whisper", type: "docs" },
      { label: "faster-whisper Benchmarks", url: "https://github.com/SYSTRAN/faster-whisper#benchmarks", type: "benchmark" },
      { label: "LiveKit Voice Agent Template", url: "https://github.com/livekit/agents", type: "docs" },
    ],
  },
  {
    id: "whisper-turbo",
    name: "Whisper Turbo (OpenAI)",
    category: "open-source",
    tagline: "8× faster than Large v3 — 809M params, near-identical accuracy",
    homepageUrl: "https://github.com/openai/whisper",
    docsUrl: "https://github.com/openai/whisper",
    wer: 3.0,
    werNote: "3.0% WER English — near-identical to Large v3 (2.7%). 8× faster inference.",
    latencyMs: 100,
    latencyMsTypical: 200,
    architecture: "Encoder-decoder Transformer (809M params, distilled from Large v3)",
    params: "809M",
    license: "MIT",
    selfHostable: true,
    selfHostNote: "Full self-hosted. MIT license. Runs on consumer GPU (RTX 3090).",
    pricePerHour: 0,
    pricePerMin: 0,
    priceNote: "Free (self-hosted). GPU compute: ~$0.03–0.10/hour.",
    freeTier: "Fully free",
    streaming: false,
    streamingDetail: "Batch processing. Use with faster-whisper for streaming. 8× faster than Large v3.",
    multilingual: true,
    languages: 99,
    speakerDiarization: false,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: false,
    onPremise: true,
    onPremiseDetail: "Full on-premise. MIT license.",
    gdprCompliant: true,
    dataResidency: "Full control.",
    score: { accuracy: 9, latency: 8, multilingual: 10, sovereignty: 10, pricing: 10, streaming: 5 },
    description: "Whisper Turbo (large-v3-turbo) is a distilled variant of Large v3 with 809M parameters — 8× faster inference with only 0.3% WER degradation. Ideal for production deployments where GPU resources are limited. Combine with faster-whisper for streaming capability.",
    descriptionFr: "Whisper Turbo (large-v3-turbo) est une variante distillée de Large v3 avec 809M paramètres — 8× plus rapide en inférence avec seulement 0,3% de dégradation WER. Idéal pour les déploiements production où les ressources GPU sont limitées. Combiner avec faster-whisper pour le streaming.",
    strengths: ["8× faster than Large v3", "3.0% WER — near-identical accuracy", "809M params — lighter GPU requirement", "MIT license", "99 languages"],
    strengthsFr: ["8× plus rapide que Large v3", "3,0% WER — précision quasi-identique", "809M params — GPU moins exigeant", "Licence MIT", "99 langues"],
    weaknesses: ["Not streaming-native", "Slightly lower accuracy than Large v3", "No speaker diarization", "Requires VAD for real-time"],
    weaknessesFr: ["Pas streaming-natif", "Précision légèrement inférieure à Large v3", "Pas de diarisation", "VAD requis pour temps réel"],
    digiDoubleRelevance: "Good balance of speed and accuracy for Phase 1 sovereign pipeline. 8× faster than Large v3 reduces GPU cost. Use with faster-whisper + silero-vad for streaming. Alternative to faster-whisper Large v3 when GPU budget is constrained.",
    digiDoubleRelevanceFr: "Bon équilibre vitesse/précision pour le pipeline souverain Phase 1. 8× plus rapide que Large v3 réduit le coût GPU. Utiliser avec faster-whisper + silero-vad pour le streaming. Alternative à faster-whisper Large v3 quand le budget GPU est contraint.",
    digiDoubleAxis: "Phase 1 MVP — ASR souverain léger",
    benchmarkRef: "OpenAI Whisper Turbo release notes, Oct 2024",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Whisper large-v3-turbo released Oct 2024. 809M params (distilled from Large v3). 8× faster inference. WER 3.0% English (OpenAI). Available on HuggingFace and via faster-whisper.",
    sources: [
      { label: "Whisper Turbo HuggingFace", url: "https://huggingface.co/openai/whisper-large-v3-turbo", type: "docs" },
      { label: "OpenAI Whisper GitHub", url: "https://github.com/openai/whisper", type: "docs" },
      { label: "HuggingFace Open ASR Leaderboard", url: "https://huggingface.co/spaces/hf-audio/open_asr_leaderboard", type: "benchmark" },
    ],
  },
  {
    id: "audiogami",
    name: "Audiogami (Gamilab)",
    category: "open-source",
    tagline: "Swiss-hosted Whisper variant — production-ready, DigiDouble Phase 1",
    homepageUrl: "https://gamilab.com",
    docsUrl: "https://gamilab.com",
    wer: 3.5,
    werNote: "~3.5% WER estimated (based on Whisper Large v3 with Swiss-specific fine-tuning). French/German optimized.",
    latencyMs: 200,
    latencyMsTypical: 400,
    architecture: "Whisper Large v3 + Swiss-specific fine-tuning (Gamilab proprietary)",
    params: "1.5B (Whisper base)",
    license: "Proprietary (Gamilab)",
    selfHostable: true,
    selfHostNote: "Swiss-hosted (Exoscale). Full data sovereignty. Production deployment by Gamilab.",
    pricePerHour: 0,
    pricePerMin: 0,
    priceNote: "Included in Gamilab partnership. No per-use pricing for DigiDouble.",
    freeTier: "Partnership-based",
    streaming: true,
    streamingDetail: "Production streaming deployment. Swiss-hosted on Exoscale. French/German/Swiss German optimized.",
    multilingual: true,
    languages: 10,
    speakerDiarization: false,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: true,
    onPremise: true,
    onPremiseDetail: "Swiss-hosted (Exoscale). Full Swiss data sovereignty. GDPR + nLPD compliant.",
    gdprCompliant: true,
    dataResidency: "Switzerland (Exoscale). Full nLPD compliance.",
    score: { accuracy: 8, latency: 6, multilingual: 5, sovereignty: 10, pricing: 10, streaming: 8 },
    description: "Audiogami is Gamilab's production ASR service, based on Whisper Large v3 with Swiss-specific optimizations. Already deployed for DigiDouble Phase 1. Swiss-hosted on Exoscale with full nLPD/GDPR compliance. French, German, and Swiss German optimized. The primary ASR component for DigiDouble MVP.",
    descriptionFr: "Audiogami est le service ASR de production de Gamilab, basé sur Whisper Large v3 avec des optimisations spécifiques suisses. Déjà déployé pour la Phase 1 DigiDouble. Hébergé en Suisse sur Exoscale avec conformité nLPD/RGPD complète. Optimisé pour le français, l'allemand et le suisse-allemand. Le composant ASR principal du MVP DigiDouble.",
    strengths: ["Swiss sovereignty (Exoscale)", "nLPD + GDPR compliant", "French/German/Swiss German optimized", "Already in production for DigiDouble", "Partnership pricing (included)"],
    strengthsFr: ["Souveraineté suisse (Exoscale)", "Conformité nLPD + RGPD", "Optimisé français/allemand/suisse-allemand", "Déjà en production pour DigiDouble", "Tarification partenariat (inclus)"],
    weaknesses: ["Proprietary Gamilab service", "Limited language coverage (10)", "200ms latency (vs 75ms Deepgram)", "No public documentation"],
    weaknessesFr: ["Service propriétaire Gamilab", "Couverture linguistique limitée (10)", "200ms latence (vs 75ms Deepgram)", "Pas de documentation publique"],
    digiDoubleRelevance: "PRIMARY ASR for DigiDouble Phase 1 MVP. Already in production. Swiss sovereignty + French/German optimization = perfect fit. Benchmark against Deepgram Nova-3 to quantify latency trade-off (200ms vs 75ms). Consider faster-whisper as sovereign fallback.",
    digiDoubleRelevanceFr: "ASR PRINCIPAL pour le MVP Phase 1 DigiDouble. Déjà en production. Souveraineté suisse + optimisation français/allemand = parfaitement adapté. Benchmarker contre Deepgram Nova-3 pour quantifier le compromis latence (200ms vs 75ms). Considérer faster-whisper comme fallback souverain.",
    digiDoubleAxis: "Phase 1 MVP — ASR principal",
    benchmarkRef: "Gamilab production deployment, 2025",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Audiogami in production for DigiDouble Phase 1 (2025). Swiss-hosted on Exoscale. WER ~3.5% estimated (Whisper Large v3 base + Swiss fine-tuning). No public benchmarks available.",
    sources: [
      { label: "Gamilab Website", url: "https://gamilab.com", type: "docs" },
      { label: "Exoscale Swiss Cloud", url: "https://www.exoscale.com", type: "docs" },
    ],
  },
  {
    id: "voxtral-asr",
    name: "Voxtral ASR (Mistral)",
    category: "open-source",
    tagline: "European open-weights ASR — French/German native, Mistral ecosystem",
    homepageUrl: "https://mistral.ai",
    docsUrl: "https://docs.mistral.ai",
    wer: 5.0,
    werNote: "~5% WER estimated on French/German (announced March 2026, benchmarks pending).",
    latencyMs: 120,
    latencyMsTypical: 250,
    architecture: "Mistral multimodal (speech encoder + LLM decoder, open-weights)",
    params: "~7B estimated",
    license: "Apache 2.0 (open-weights)",
    selfHostable: true,
    selfHostNote: "Open-weights, self-hostable. EU-origin model. Mistral API also available.",
    pricePerHour: 0,
    pricePerMin: 0.003,
    priceNote: "Self-hosted: free. Mistral API: ~$0.003/min (estimated). Open-weights for sovereign deployment.",
    freeTier: "Open-weights — free self-hosted",
    streaming: true,
    streamingDetail: "Streaming-capable (announced). Part of Voxtral full-stack (ASR + TTS). 120ms estimated latency.",
    multilingual: true,
    languages: 30,
    speakerDiarization: false,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: false,
    onPremise: true,
    onPremiseDetail: "Open-weights — full on-premise. EU-origin (French company).",
    gdprCompliant: true,
    dataResidency: "EU (Mistral, France). Full control if self-hosted.",
    score: { accuracy: 7, latency: 8, multilingual: 6, sovereignty: 9, pricing: 9, streaming: 7 },
    description: "Voxtral ASR is Mistral's open-weights speech recognition model (announced March 2026). Part of the Voxtral full-stack (ASR + TTS). European open-weights with native French/German support. Creates a potential full-stack sovereign pipeline: Voxtral ASR → Mistral LLM → Voxtral TTS. Very new — production testing required.",
    descriptionFr: "Voxtral ASR est le modèle de reconnaissance vocale open-weights de Mistral (annoncé mars 2026). Fait partie du stack complet Voxtral (ASR + TTS). Open-weights européen avec support natif français/allemand. Crée un pipeline souverain full-stack potentiel : Voxtral ASR → Mistral LLM → Voxtral TTS. Très récent — tests production requis.",
    strengths: ["European open-weights (Apache 2.0)", "Native French/German support", "Full-stack Mistral ecosystem (ASR+LLM+TTS)", "Self-hostable — full sovereignty", "~120ms estimated latency"],
    strengthsFr: ["Open-weights européen (Apache 2.0)", "Support natif français/allemand", "Écosystème Mistral full-stack (ASR+LLM+TTS)", "Self-hostable — souveraineté totale", "~120ms latence estimée"],
    weaknesses: ["Very new (March 2026) — no production track record", "Benchmarks pending", "~7B params — significant GPU requirement", "No speaker diarization"],
    weaknessesFr: ["Très récent (mars 2026) — pas de track record production", "Benchmarks en attente", "~7B params — GPU significatif requis", "Pas de diarisation"],
    digiDoubleRelevance: "High priority evaluation for Phase 1 MVP. Creates full-stack sovereign pipeline with Voxtral TTS + Mistral LLM. French/German native support critical for Swiss market. Very new — needs 3-month production testing before Phase 1 deployment.",
    digiDoubleRelevanceFr: "Évaluation haute priorité pour le MVP Phase 1. Crée un pipeline souverain full-stack avec Voxtral TTS + Mistral LLM. Support natif français/allemand critique pour le marché suisse. Très récent — 3 mois de tests production requis avant déploiement Phase 1.",
    digiDoubleAxis: "Phase 1 MVP — Stack Mistral souverain",
    benchmarkRef: "Mistral AI announcement, Mar 26, 2026",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Voxtral announced Mar 26, 2026 by Mistral AI. Apache 2.0 open-weights. Part of Voxtral full-stack (ASR+TTS). Production benchmarks not yet available. Mistral API pricing estimated.",
    sources: [
      { label: "Mistral Voxtral Announcement", url: "https://mistral.ai/news/voxtral", type: "news" },
      { label: "Mistral AI Docs", url: "https://docs.mistral.ai", type: "docs" },
      { label: "Mistral API Pricing", url: "https://mistral.ai/technology/#pricing", type: "pricing" },
    ],
  },
  // ─── INWORLD STT ─────────────────────────────────────────────
  {
    id: "inworld-stt",
    name: "Inworld STT",
    category: "cloud-api",
    tagline: "Voice profiling STT — <100ms, Realtime API $0.015/min, clonage vocal natif, 100+ langues",
    homepageUrl: "https://inworld.ai/speech-to-text",
    docsUrl: "https://docs.inworld.ai/stt",
    wer: 5.0,
    werNote: "~5% WER (multi-provider routing: Whisper large-v3 + AssemblyAI Universal Streaming). Accuracy depends on selected backend model.",
    latencyMs: 92,
    latencyMsTypical: 150,
    architecture: "Multi-provider router (Whisper large-v3 + AssemblyAI Universal Streaming + proprietary)",
    params: "N/A (cloud router)",
    license: "Commercial",
    selfHostable: false,
    selfHostNote: "Cloud API only. Zero Data Retention (ZDR) available — audio never stored, processed in real time.",
    pricePerHour: 0.36,
    pricePerMin: 0.006,
    priceNote: "STT seul : $0.006–0.012/min selon modèle. Realtime API (pipeline complet STT+LLM+TTS) : à partir de $0.015/min (vs OpenAI Realtime $0.06/min). Growth plan : 40% de réduction ($1,500 crédits/mois). On-prem : Enterprise uniquement. Free tier disponible.",
    freeTier: "Free tier available. Growth plan: $1,500 credits/month with 40% off.",
    streaming: true,
    streamingDetail: "Bidirectional WebSocket streaming. <100ms documented latency (92ms TTFA). Interim results with voice profile signals on every audio chunk. Semantic + acoustic VAD. Configurable endpointing.",
    multilingual: true,
    languages: 100,
    speakerDiarization: true,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: true,
    onPremise: false,
    onPremiseDetail: "No on-premise. ZDR ensures audio never stored. EU data residency on Enterprise.",
    gdprCompliant: true,
    dataResidency: "US (default). EU data residency on Enterprise. ZDR available — audio never stored.",
    score: { accuracy: 9, latency: 10, multilingual: 10, sovereignty: 3, pricing: 7, streaming: 10 },
    description: "Inworld STT (2025–2026) is the most feature-rich cloud STT API for interactive voice agents. Sub-100ms documented latency, 100+ languages via multi-provider routing (Whisper large-v3 + AssemblyAI). Unique real-time voice profiling extracts emotion (happy/calm/angry/frustrated), accent, age, pitch, and vocal style on every streaming chunk. Realtime API (full pipeline STT+LLM+TTS) from $0.015/min — 4x cheaper than OpenAI Realtime ($0.06/min). Native voice cloning: built-in + cloned + custom voices (up to 3,000 custom voices on Growth plan). RAG via function calling (tool calling mid-conversation). ZDR support. On-premise available on Enterprise. Drop-in compatible with OpenAI Realtime API.",
    descriptionFr: "Inworld STT (2025–2026) est l'API STT cloud la plus riche en fonctionnalités pour les agents vocaux interactifs. Latence documentée <100ms, 100+ langues via routage multi-fournisseur (Whisper large-v3 + AssemblyAI). Voice profiling temps réel unique extrait émotion, accent, âge, pitch et style vocal sur chaque chunk. Realtime API (pipeline complet STT+LLM+TTS) à partir de 0,015$/min — 4x moins cher qu'OpenAI Realtime (0,06$/min). Clonage vocal natif : voix intégrées + clonées + custom (jusqu'à 3 000 voix custom sur Growth). RAG via function calling mid-conversation. Support ZDR. On-premise disponible en Enterprise. Compatible drop-in avec l'API Realtime OpenAI.",
    strengths: [
      "<100ms documented streaming latency (92ms TTFA)",
      "Realtime API $0.015/min — 4x cheaper than OpenAI Realtime",
      "Native voice cloning : built-in + cloned + custom (up to 3,000 voices)",
      "RAG via function calling mid-conversation",
      "Voice profiling: emotion, accent, age, pitch, vocal style",
      "100+ languages (Whisper large-v3 backend)",
      "Semantic + acoustic VAD",
      "ZDR — audio never stored",
      "On-premise available (Enterprise)",
      "Drop-in compatible with OpenAI Realtime API",
      "Condition Router: route by emotion/language/tier"
    ],
    strengthsFr: [
      "<100ms latence streaming documentée (92ms TTFA)",
      "Realtime API 0,015$/min — 4x moins cher qu'OpenAI Realtime",
      "Clonage vocal natif : voix intégrées + clonées + custom (jusqu'à 3 000 voix)",
      "RAG via function calling mid-conversation",
      "Voice profiling : émotion, accent, âge, pitch, style vocal",
      "100+ langues (backend Whisper large-v3)",
      "VAD sémantique + acoustique",
      "ZDR — audio jamais stocké",
      "On-premise disponible (Enterprise)",
      "Compatible drop-in avec l'API Realtime OpenAI",
      "Condition Router : routage par émotion/langue/tier"
    ],
    weaknesses: [
      "On-premise Enterprise only (not available on lower tiers)",
      "Pricing less transparent than Deepgram (credit-based system)",
      "Multi-provider adds latency variability",
      "Vendor lock-in risk if using full Inworld stack (STT+TTS+LLM)",
      "No fine-tuning on custom data",
      "400%+ price increase reported in 2026 (market consolidation risk)"
    ],
    weaknessesFr: [
      "On-premise Enterprise uniquement (pas disponible sur les tiers inférieurs)",
      "Tarification moins transparente que Deepgram (système de crédits)",
      "Multi-fournisseur ajoute de la variabilité de latence",
      "Risque de vendor lock-in si utilisation de la stack Inworld complète",
      "Pas de fine-tuning sur données personnalisées",
      "Hausse de prix de 400%+ signalée en 2026 (risque de consolidation marché)"
    ],
    digiDoubleRelevance: "High strategic value for DigiDouble Axis 2 (Avatar Behavior) and Emotional Toolbox. Voice profiling enables real-time emotion detection without a separate model — feeding directly into avatar expression selection and LLM prompt conditioning. <100ms latency compatible with Phase 1 target. Evaluate as primary STT if emotion-aware routing is required in Phase 1.",
    digiDoubleRelevanceFr: "Valeur stratégique élevée pour l'Axe 2 DigiDouble (Comportement Avatar) et l'Emotional Toolbox. Le voice profiling permet la détection d'émotion temps réel sans modèle séparé — alimentant directement la sélection d'expression avatar et le conditionnement des prompts LLM. Latence <100ms compatible avec la cible Phase 1.",
    digiDoubleAxis: "Phase 1 MVP — STT émotionnel + Axe 2 Avatar Behavior",
    benchmarkRef: "https://inworld.ai/resources/best-speech-to-text-apis",
    voiceAgentApi: {
      available: true,
      price: "$0.015/min",
      note: "Inworld Realtime API : pipeline complet STT+LLM+TTS en 1 WebSocket à partir de $0.015/min (vs OpenAI Realtime $0.06/min). Choix de centaines de LLMs (OpenAI, Anthropic, Google, Mistral, xAI). Clonage vocal natif (built-in + cloné + custom). Function calling + semantic turn detection. Compatible drop-in OpenAI Realtime API. WebSocket public + WebRTC/SIP en early access.",
      url: "https://inworld.ai/realtime-api",
    },
    dataUpdatedAt: "2026-05-02",
    dataUpdateNote: "Realtime API $0.015/min confirmé (mai 2026) — 4x moins cher qu'OpenAI Realtime. Clonage vocal natif confirmé : built-in + cloné + custom (jusqu'à 3 000 voix custom sur Growth). RAG via function calling mid-conversation. On-premise disponible en Enterprise. ZDR sur tous les plans. EU data residency sur Enterprise. Hausse de prix 400%+ signalée en 2026.",
    sources: [
      { label: "Inworld Realtime API", url: "https://inworld.ai/realtime-api", type: "docs" },
      { label: "Inworld STT Product Page", url: "https://inworld.ai/speech-to-text", type: "docs" },
      { label: "Inworld Pricing (mai 2026)", url: "https://inworld.ai/pricing", type: "pricing" },
      { label: "Inworld STT Benchmark Article", url: "https://inworld.ai/resources/best-speech-to-text-apis", type: "benchmark" },
      { label: "Artificial Analysis STT", url: "https://artificialanalysis.ai/speech-to-text", type: "benchmark" },
      { label: "Inworld vs OpenAI Realtime API Comparison", url: "https://inworld.ai/realtime-api", type: "benchmark" },
    ],
  },
];
export function getSTTData(): STTData[] {
  return sttDatabase;
}

export function getSTTById(id: string): STTData | undefined {
  return sttDatabase.find((s) => s.id === id);
}

export function getSTTByCategory(category: STTCategory): STTData[] {
  return sttDatabase.filter((s) => s.category === category);
}
