// ============================================================
// sttData.ts — DigiDouble Research Portal
// Données centralisées STT / ASR (Speech-to-Text) 2025–2026
// Sources : Artificial Analysis, benchmarks officiels, docs
// ============================================================

export type STTCategory = "cloud-api" | "open-source";

export interface STTScore {
  accuracy: number;       // 1–10 (WER normalisé)
  latency: number;        // 1–10 (10 = <50ms streaming, 1 = >1s)
  multilingual: number;   // 1–10
  sovereignty: number;    // 1–10 (10 = full self-hosted)
  pricing: number;        // 1–10 (10 = gratuit)
  streaming: number;      // 1–10 (support streaming temps réel)
}

export interface STTData {
  id: string;
  name: string;
  category: STTCategory;
  tagline: string;
  homepageUrl: string;
  docsUrl: string;
  // Specs techniques
  wer: number;              // Word Error Rate % (lower = better), 0 if N/A
  werNote: string;
  latencyMs: number;        // Latence streaming (TTFA ou P90) en ms
  latencyMsTypical: number;
  architecture: string;
  params: string;
  license: string;
  selfHostable: boolean;
  selfHostNote: string;
  // Pricing
  pricePerHour: number;     // $ par heure d'audio
  pricePerMin: number;
  priceNote: string;
  freeTier: string;
  // Capacités
  streaming: boolean;
  streamingDetail: string;
  multilingual: boolean;
  languages: number;
  speakerDiarization: boolean;
  wordTimestamps: boolean;
  punctuation: boolean;
  customVocabulary: boolean;
  // Souveraineté
  onPremise: boolean;
  onPremiseDetail: string;
  gdprCompliant: boolean;
  dataResidency: string;
  // Scores
  score: STTScore;
  // Description
  description: string;
  descriptionFr: string;
  strengths: string[];
  strengthsFr: string[];
  weaknesses: string[];
  weaknessesFr: string[];
  // Pertinence DigiDouble
  digiDoubleRelevance: string;
  digiDoubleRelevanceFr: string;
  digiDoubleAxis: string;
  benchmarkRef?: string;
}

const sttDatabase: STTData[] = [
  // ─── CLOUD API ───────────────────────────────────────────────
  {
    id: "deepgram-nova3",
    name: "Deepgram Nova-3",
    category: "cloud-api",
    tagline: "Fastest streaming ASR — 75ms, 36 languages, voice agents optimized",
    homepageUrl: "https://deepgram.com",
    docsUrl: "https://developers.deepgram.com",
    wer: 7.2,
    werNote: "7.2% WER on English (Koenecke benchmark). 12–18% on noisy/accented speech.",
    latencyMs: 75,
    latencyMsTypical: 200,
    architecture: "End-to-end deep learning (proprietary), streaming-native",
    params: "N/A (cloud)",
    license: "Commercial",
    selfHostable: true,
    selfHostNote: "On-premise deployment available (enterprise). Self-hosted via Docker.",
    pricePerHour: 0.216,
    pricePerMin: 0.0036,
    priceNote: "$0.0036/min (Pay-as-you-go). $0.0024/min (Growth plan). On-premise: custom pricing.",
    freeTier: "$200 credit on signup",
    streaming: true,
    streamingDetail: "WebSocket streaming. 75ms P90 latency. Interim results with endpointing. Voice Activity Detection (VAD) built-in.",
    multilingual: true,
    languages: 36,
    speakerDiarization: true,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: true,
    onPremise: true,
    onPremiseDetail: "Self-hosted Docker deployment. Enterprise on-premise available. Partial sovereignty.",
    gdprCompliant: true,
    dataResidency: "US (default). EU data residency available.",
    score: { accuracy: 8, latency: 10, multilingual: 7, sovereignty: 5, pricing: 7, streaming: 10 },
    description: "Deepgram Nova-3 is the industry reference for real-time voice agent ASR. 75ms P90 streaming latency, 36 languages, built-in VAD and endpointing. Optimized for conversational AI pipelines (LiveKit, Pipecat integrations). On-premise option available for partial sovereignty. Used by Tavus, Simli, and most commercial avatar platforms.",
    descriptionFr: "Deepgram Nova-3 est la référence industrie pour l'ASR d'agents vocaux temps réel. 75ms P90 en streaming, 36 langues, VAD et endpointing intégrés. Optimisé pour les pipelines IA conversationnels (intégrations LiveKit, Pipecat). Option on-premise disponible pour une souveraineté partielle. Utilisé par Tavus, Simli et la plupart des plateformes d'avatars commerciales.",
    strengths: ["75ms P90 streaming latency", "Built-in VAD + endpointing", "36 languages", "On-premise option", "LiveKit/Pipecat native integration", "Speaker diarization + word timestamps"],
    strengthsFr: ["75ms P90 latence streaming", "VAD + endpointing intégrés", "36 langues", "Option on-premise", "Intégration native LiveKit/Pipecat", "Diarisation + timestamps mot-à-mot"],
    weaknesses: ["Cloud-first (sovereignty limited)", "7.2% WER on English (not best-in-class)", "French/German WER higher (~15%)", "No open-weights"],
    weaknessesFr: ["Cloud-first (souveraineté limitée)", "7,2% WER en anglais (pas le meilleur)", "WER français/allemand plus élevé (~15%)", "Pas d'open-weights"],
    digiDoubleRelevance: "Primary candidate for Phase 1 MVP ASR. 75ms latency is critical for sub-2s pipeline. On-premise option aligns with Swiss sovereignty requirements. Audiogami (Gamilab) already in production — Deepgram as fallback/comparison.",
    digiDoubleRelevanceFr: "Candidat principal pour l'ASR du MVP Phase 1. 75ms latence critique pour le pipeline <2s. Option on-premise alignée avec les exigences de souveraineté suisse. Audiogami (Gamilab) déjà en production — Deepgram comme fallback/comparaison.",
    digiDoubleAxis: "Phase 1 MVP — ASR streaming",
    benchmarkRef: "Inworld benchmark 2026 + Koenecke et al.",
  },
  {
    id: "assemblyai",
    name: "AssemblyAI Universal-2",
    category: "cloud-api",
    tagline: "Best WER accuracy — 4.9%, real-time streaming, LeMUR AI features",
    homepageUrl: "https://www.assemblyai.com",
    docsUrl: "https://www.assemblyai.com/docs",
    wer: 4.9,
    werNote: "4.9% WER on English (best-in-class cloud). Universal-2 model.",
    latencyMs: 150,
    latencyMsTypical: 300,
    architecture: "Universal-2 (proprietary transformer, multi-task)",
    params: "N/A (cloud)",
    license: "Commercial",
    selfHostable: false,
    selfHostNote: "Cloud only. No on-premise option.",
    pricePerHour: 0.372,
    pricePerMin: 0.0062,
    priceNote: "$0.0062/min real-time streaming. $0.0037/min async. LeMUR features extra.",
    freeTier: "$50 credit on signup",
    streaming: true,
    streamingDetail: "WebSocket real-time streaming. Partial transcripts with 150ms latency. Endpointing configurable.",
    multilingual: true,
    languages: 99,
    speakerDiarization: true,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: true,
    onPremise: false,
    onPremiseDetail: "Cloud only. No on-premise.",
    gdprCompliant: true,
    dataResidency: "US (default). EU data residency on request.",
    score: { accuracy: 10, latency: 7, multilingual: 10, sovereignty: 1, pricing: 5, streaming: 8 },
    description: "AssemblyAI Universal-2 achieves 4.9% WER — best-in-class accuracy among cloud ASR APIs. 99 languages, speaker diarization, sentiment analysis, and LeMUR AI features (summarization, Q&A on transcripts). 150ms streaming latency. No on-premise option limits sovereignty. Best choice when accuracy is the primary requirement.",
    descriptionFr: "AssemblyAI Universal-2 atteint 4,9% WER — meilleure précision parmi les APIs ASR cloud. 99 langues, diarisation, analyse de sentiment et fonctionnalités LeMUR (résumé, Q&R sur transcriptions). 150ms de latence streaming. Pas d'option on-premise. Meilleur choix quand la précision est la priorité.",
    strengths: ["4.9% WER — best-in-class accuracy", "99 languages", "Speaker diarization + sentiment", "LeMUR AI features (summarization, Q&A)", "Word-level timestamps"],
    strengthsFr: ["4,9% WER — meilleure précision", "99 langues", "Diarisation + sentiment", "Fonctionnalités LeMUR (résumé, Q&R)", "Timestamps mot-à-mot"],
    weaknesses: ["Cloud only — no sovereignty", "150ms latency (2× Deepgram)", "$0.0062/min — more expensive than Deepgram", "No on-premise option"],
    weaknessesFr: ["Cloud uniquement — pas de souveraineté", "150ms latence (2× Deepgram)", "$0,0062/min — plus cher que Deepgram", "Pas d'option on-premise"],
    digiDoubleRelevance: "Accuracy reference for DigiDouble validation. 4.9% WER useful for benchmarking Audiogami and Whisper local. Not suitable for production due to no sovereignty and higher latency than Deepgram.",
    digiDoubleRelevanceFr: "Référence précision pour la validation DigiDouble. 4,9% WER utile pour benchmarker Audiogami et Whisper local. Non adapté à la production en raison de l'absence de souveraineté et de latence plus élevée que Deepgram.",
    digiDoubleAxis: "Référence précision",
    benchmarkRef: "AssemblyAI docs + Koenecke benchmark 2025",
  },
  {
    id: "google-stt",
    name: "Google Speech-to-Text v2",
    category: "cloud-api",
    tagline: "Chirp 2 model — 125 languages, streaming, Google ecosystem",
    homepageUrl: "https://cloud.google.com/speech-to-text",
    docsUrl: "https://cloud.google.com/speech-to-text/docs",
    wer: 6.8,
    werNote: "6.8% WER English (Chirp 2). Competitive on multilingual.",
    latencyMs: 200,
    latencyMsTypical: 400,
    architecture: "Chirp 2 (USM — Universal Speech Model, 2B params)",
    params: "2B (USM)",
    license: "Commercial",
    selfHostable: false,
    selfHostNote: "Cloud only (GCP). No on-premise.",
    pricePerHour: 0.36,
    pricePerMin: 0.006,
    priceNote: "$0.006/min (Chirp 2). $0.004/min (standard). Free: 60 min/month.",
    freeTier: "60 minutes/month",
    streaming: true,
    streamingDetail: "Bidirectional streaming gRPC. 200ms typical latency. Interim results available.",
    multilingual: true,
    languages: 125,
    speakerDiarization: true,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: true,
    onPremise: false,
    onPremiseDetail: "GCP cloud only.",
    gdprCompliant: true,
    dataResidency: "EU region available (Belgium, Netherlands).",
    score: { accuracy: 8, latency: 6, multilingual: 10, sovereignty: 2, pricing: 6, streaming: 7 },
    description: "Google STT v2 with Chirp 2 (USM 2B) covers 125 languages with competitive accuracy. gRPC bidirectional streaming. Deep integration with Google ecosystem (Dialogflow, Vertex AI). 200ms typical streaming latency. EU data residency available. No on-premise option.",
    descriptionFr: "Google STT v2 avec Chirp 2 (USM 2B) couvre 125 langues avec une précision compétitive. Streaming bidirectionnel gRPC. Intégration profonde avec l'écosystème Google (Dialogflow, Vertex AI). 200ms de latence streaming typique. Résidence données EU disponible. Pas d'option on-premise.",
    strengths: ["125 languages — widest coverage", "Chirp 2 (USM 2B) quality", "EU data residency available", "gRPC streaming", "Google ecosystem integration"],
    strengthsFr: ["125 langues — couverture la plus large", "Chirp 2 (USM 2B) qualité", "Résidence données EU disponible", "Streaming gRPC", "Intégration écosystème Google"],
    weaknesses: ["200ms latency (2.7× Deepgram)", "Cloud only, no sovereignty", "Complex pricing tiers", "No open-weights"],
    weaknessesFr: ["200ms latence (2,7× Deepgram)", "Cloud uniquement, pas de souveraineté", "Tarification complexe", "Pas d'open-weights"],
    digiDoubleRelevance: "Useful for multilingual DigiDouble deployments requiring 100+ language support. EU data residency partially addresses Swiss sovereignty. Not recommended for Phase 1 MVP due to higher latency than Deepgram.",
    digiDoubleRelevanceFr: "Utile pour les déploiements DigiDouble multilingues nécessitant 100+ langues. Résidence données EU adresse partiellement la souveraineté suisse. Non recommandé pour le MVP Phase 1 en raison d'une latence plus élevée que Deepgram.",
    digiDoubleAxis: "Multilingue — option secondaire",
    benchmarkRef: "Google Cloud docs + Koenecke benchmark 2025",
  },
  {
    id: "azure-stt",
    name: "Azure Speech (Microsoft)",
    category: "cloud-api",
    tagline: "Enterprise-grade STT — 100+ languages, custom models, EU sovereign",
    homepageUrl: "https://azure.microsoft.com/en-us/products/ai-services/speech-to-text",
    docsUrl: "https://learn.microsoft.com/en-us/azure/ai-services/speech-service/",
    wer: 5.9,
    werNote: "5.9% WER English. Strong on Swiss German with custom model.",
    latencyMs: 180,
    latencyMsTypical: 350,
    architecture: "Custom Neural Voice + Universal model (proprietary)",
    params: "N/A (cloud)",
    license: "Commercial",
    selfHostable: true,
    selfHostNote: "Azure Stack / disconnected containers available. Partial on-premise.",
    pricePerHour: 1.00,
    pricePerMin: 0.0167,
    priceNote: "$1.00/hour standard. $1.50/hour custom model. Commitment tiers available.",
    freeTier: "5 hours/month free",
    streaming: true,
    streamingDetail: "WebSocket + REST streaming. 180ms typical latency. Continuous recognition mode.",
    multilingual: true,
    languages: 100,
    speakerDiarization: true,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: true,
    onPremise: true,
    onPremiseDetail: "Azure Stack + disconnected containers. Swiss data center available (Zurich).",
    gdprCompliant: true,
    dataResidency: "EU (Switzerland North — Zurich available).",
    score: { accuracy: 9, latency: 7, multilingual: 9, sovereignty: 6, pricing: 3, streaming: 8 },
    description: "Azure Speech offers enterprise-grade STT with 100+ languages, custom model training, and Swiss data center (Zurich). 5.9% WER on English. Disconnected container deployment for partial sovereignty. Most expensive option but strongest enterprise compliance. Swiss German custom model available.",
    descriptionFr: "Azure Speech offre un STT enterprise avec 100+ langues, entraînement de modèles personnalisés et datacenter suisse (Zurich). 5,9% WER en anglais. Déploiement en conteneur déconnecté pour une souveraineté partielle. Option la plus chère mais la plus forte en conformité enterprise. Modèle personnalisé suisse-allemand disponible.",
    strengths: ["Swiss data center (Zurich)", "Custom model training", "5.9% WER accuracy", "Disconnected container deployment", "Swiss German support"],
    strengthsFr: ["Datacenter suisse (Zurich)", "Entraînement modèle personnalisé", "5,9% WER précision", "Déploiement conteneur déconnecté", "Support suisse-allemand"],
    weaknesses: ["Most expensive ($1/hour)", "180ms latency", "Complex setup for on-premise", "Microsoft ecosystem dependency"],
    weaknessesFr: ["Plus cher ($1/heure)", "180ms latence", "Configuration complexe on-premise", "Dépendance écosystème Microsoft"],
    digiDoubleRelevance: "Strong candidate for Swiss institutional deployments requiring data residency in Switzerland. Swiss German custom model critical for DigiDouble Swiss market. Too expensive for high-volume production.",
    digiDoubleRelevanceFr: "Candidat fort pour les déploiements institutionnels suisses nécessitant la résidence des données en Suisse. Modèle suisse-allemand critique pour le marché suisse DigiDouble. Trop cher pour la production à volume élevé.",
    digiDoubleAxis: "Souveraineté suisse — institutionnel",
    benchmarkRef: "Microsoft docs + Azure pricing 2026",
  },
  // ─── OPEN SOURCE ─────────────────────────────────────────────
  {
    id: "whisper-large-v3",
    name: "Whisper Large v3 (OpenAI)",
    category: "open-source",
    tagline: "Open-source reference — 99 languages, 2.7% WER, self-hostable",
    homepageUrl: "https://github.com/openai/whisper",
    docsUrl: "https://platform.openai.com/docs/guides/speech-to-text",
    wer: 2.7,
    werNote: "2.7% WER English (LibriSpeech clean). Best open-source accuracy. 8–15% on noisy/accented.",
    latencyMs: 300,
    latencyMsTypical: 800,
    architecture: "Encoder-decoder Transformer (1.5B params)",
    params: "1.5B",
    license: "MIT",
    selfHostable: true,
    selfHostNote: "Full self-hosted. GPU recommended (A100 for real-time). CPU possible with quantization.",
    pricePerHour: 0,
    pricePerMin: 0,
    priceNote: "Free (self-hosted). OpenAI API: $0.006/min. GPU compute cost: ~$0.10–0.50/hour.",
    freeTier: "Fully free (self-hosted)",
    streaming: false,
    streamingDetail: "Batch processing only. Not streaming-native. Use faster-whisper or whisper-streaming for near-real-time.",
    multilingual: true,
    languages: 99,
    speakerDiarization: false,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: false,
    onPremise: true,
    onPremiseDetail: "Full on-premise. MIT license. Complete sovereignty.",
    gdprCompliant: true,
    dataResidency: "Full control — data never leaves your infrastructure.",
    score: { accuracy: 10, latency: 4, multilingual: 10, sovereignty: 10, pricing: 10, streaming: 3 },
    description: "Whisper Large v3 is the open-source ASR reference with 2.7% WER on English (best open-source). MIT license, 99 languages, full self-hosting. Not streaming-native — requires faster-whisper or whisper-streaming for real-time use. Audiogami (Gamilab) is based on Whisper with Swiss-specific optimizations.",
    descriptionFr: "Whisper Large v3 est la référence ASR open-source avec 2,7% WER en anglais (meilleur open-source). Licence MIT, 99 langues, self-hosting complet. Pas streaming-natif — nécessite faster-whisper ou whisper-streaming pour l'usage temps réel. Audiogami (Gamilab) est basé sur Whisper avec des optimisations spécifiques suisses.",
    strengths: ["2.7% WER — best open-source accuracy", "MIT license — full sovereignty", "99 languages", "Free (self-hosted)", "Audiogami (Gamilab) production-ready variant"],
    strengthsFr: ["2,7% WER — meilleure précision open-source", "Licence MIT — souveraineté totale", "99 langues", "Gratuit (self-hosted)", "Audiogami (Gamilab) variante production"],
    weaknesses: ["Not streaming-native (batch)", "300ms+ latency for real-time use", "GPU required for production speed", "No speaker diarization"],
    weaknessesFr: ["Pas streaming-natif (batch)", "300ms+ latence pour usage temps réel", "GPU requis pour vitesse production", "Pas de diarisation"],
    digiDoubleRelevance: "Foundation of Audiogami (Gamilab) — already in production for DigiDouble. Use faster-whisper with VAD for Phase 1 streaming pipeline. Full sovereignty aligns with Swiss requirements. Benchmark against Deepgram Nova-3 for latency trade-off.",
    digiDoubleRelevanceFr: "Fondation d'Audiogami (Gamilab) — déjà en production pour DigiDouble. Utiliser faster-whisper avec VAD pour le pipeline streaming Phase 1. Souveraineté totale alignée avec les exigences suisses. Benchmarker contre Deepgram Nova-3 pour le compromis latence.",
    digiDoubleAxis: "Phase 1 MVP — Base Audiogami",
    benchmarkRef: "OpenAI Whisper paper + Koenecke benchmark 2025",
  },
  {
    id: "faster-whisper",
    name: "faster-whisper (CTranslate2)",
    category: "open-source",
    tagline: "4× faster Whisper inference — streaming-capable, CPU/GPU, production-ready",
    homepageUrl: "https://github.com/SYSTRAN/faster-whisper",
    docsUrl: "https://github.com/SYSTRAN/faster-whisper",
    wer: 2.7,
    werNote: "Same accuracy as Whisper Large v3 (identical weights, optimized inference).",
    latencyMs: 150,
    latencyMsTypical: 300,
    architecture: "CTranslate2 optimized Whisper (int8 quantization, beam search)",
    params: "1.5B (same as Whisper Large v3)",
    license: "MIT",
    selfHostable: true,
    selfHostNote: "Full self-hosted. 4× faster than original Whisper. CPU viable with int8 quantization.",
    pricePerHour: 0,
    pricePerMin: 0,
    priceNote: "Free (self-hosted). GPU compute: ~$0.05–0.20/hour with int8.",
    freeTier: "Fully free",
    streaming: true,
    streamingDetail: "Streaming mode with VAD (silero-vad). 150ms latency with chunked processing. Used in whisper-streaming and LiveKit integrations.",
    multilingual: true,
    languages: 99,
    speakerDiarization: false,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: false,
    onPremise: true,
    onPremiseDetail: "Full on-premise. MIT license.",
    gdprCompliant: true,
    dataResidency: "Full control.",
    score: { accuracy: 10, latency: 7, multilingual: 10, sovereignty: 10, pricing: 10, streaming: 7 },
    description: "faster-whisper is the production-ready variant of Whisper using CTranslate2 for 4× faster inference with the same accuracy. int8 quantization enables CPU deployment. Streaming mode with silero-vad achieves 150ms latency. Used in LiveKit voice agent templates and Audiogami-style deployments.",
    descriptionFr: "faster-whisper est la variante production de Whisper utilisant CTranslate2 pour une inférence 4× plus rapide avec la même précision. La quantification int8 permet le déploiement CPU. Le mode streaming avec silero-vad atteint 150ms de latence. Utilisé dans les templates d'agents vocaux LiveKit.",
    strengths: ["4× faster than original Whisper", "Same 2.7% WER accuracy", "CPU viable with int8", "Streaming mode with VAD", "MIT license — full sovereignty", "LiveKit integration available"],
    strengthsFr: ["4× plus rapide que Whisper original", "Même précision 2,7% WER", "CPU viable avec int8", "Mode streaming avec VAD", "Licence MIT — souveraineté totale", "Intégration LiveKit disponible"],
    weaknesses: ["150ms latency (2× Deepgram)", "No speaker diarization", "Requires VAD setup for streaming", "GPU still recommended for production"],
    weaknessesFr: ["150ms latence (2× Deepgram)", "Pas de diarisation", "Configuration VAD requise pour streaming", "GPU toujours recommandé en production"],
    digiDoubleRelevance: "Recommended for Phase 1 MVP sovereign ASR pipeline. 4× faster than base Whisper, streaming-capable with VAD. Combine with silero-vad for real-time endpointing. Full sovereignty. Benchmark: 150ms vs Deepgram 75ms — acceptable trade-off for Swiss sovereign deployment.",
    digiDoubleRelevanceFr: "Recommandé pour le pipeline ASR souverain du MVP Phase 1. 4× plus rapide que Whisper de base, streaming avec VAD. Combiner avec silero-vad pour l'endpointing temps réel. Souveraineté totale. Benchmark : 150ms vs Deepgram 75ms — compromis acceptable pour déploiement souverain suisse.",
    digiDoubleAxis: "Phase 1 MVP — ASR souverain",
    benchmarkRef: "SYSTRAN faster-whisper benchmarks 2025",
  },
  {
    id: "whisper-turbo",
    name: "Whisper Turbo (OpenAI)",
    category: "open-source",
    tagline: "8× faster than Large v3 — 809M params, near-identical accuracy",
    homepageUrl: "https://github.com/openai/whisper",
    docsUrl: "https://github.com/openai/whisper",
    wer: 3.0,
    werNote: "3.0% WER English — near-identical to Large v3 (2.7%). 8× faster inference.",
    latencyMs: 100,
    latencyMsTypical: 200,
    architecture: "Encoder-decoder Transformer (809M params, distilled from Large v3)",
    params: "809M",
    license: "MIT",
    selfHostable: true,
    selfHostNote: "Full self-hosted. MIT license. Runs on consumer GPU (RTX 3090).",
    pricePerHour: 0,
    pricePerMin: 0,
    priceNote: "Free (self-hosted). GPU compute: ~$0.03–0.10/hour.",
    freeTier: "Fully free",
    streaming: false,
    streamingDetail: "Batch processing. Use with faster-whisper for streaming. 8× faster than Large v3.",
    multilingual: true,
    languages: 99,
    speakerDiarization: false,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: false,
    onPremise: true,
    onPremiseDetail: "Full on-premise. MIT license.",
    gdprCompliant: true,
    dataResidency: "Full control.",
    score: { accuracy: 9, latency: 8, multilingual: 10, sovereignty: 10, pricing: 10, streaming: 5 },
    description: "Whisper Turbo (large-v3-turbo) is a distilled variant of Large v3 with 809M parameters — 8× faster inference with only 0.3% WER degradation. Ideal for production deployments where GPU resources are limited. Combine with faster-whisper for streaming capability.",
    descriptionFr: "Whisper Turbo (large-v3-turbo) est une variante distillée de Large v3 avec 809M paramètres — 8× plus rapide en inférence avec seulement 0,3% de dégradation WER. Idéal pour les déploiements production où les ressources GPU sont limitées. Combiner avec faster-whisper pour le streaming.",
    strengths: ["8× faster than Large v3", "3.0% WER — near-identical accuracy", "809M params — lighter GPU requirement", "MIT license", "99 languages"],
    strengthsFr: ["8× plus rapide que Large v3", "3,0% WER — précision quasi-identique", "809M params — GPU moins exigeant", "Licence MIT", "99 langues"],
    weaknesses: ["Not streaming-native", "Slightly lower accuracy than Large v3", "No speaker diarization", "Requires VAD for real-time"],
    weaknessesFr: ["Pas streaming-natif", "Précision légèrement inférieure à Large v3", "Pas de diarisation", "VAD requis pour temps réel"],
    digiDoubleRelevance: "Good balance of speed and accuracy for Phase 1 sovereign pipeline. 8× faster than Large v3 reduces GPU cost. Use with faster-whisper + silero-vad for streaming. Alternative to faster-whisper Large v3 when GPU budget is constrained.",
    digiDoubleRelevanceFr: "Bon équilibre vitesse/précision pour le pipeline souverain Phase 1. 8× plus rapide que Large v3 réduit le coût GPU. Utiliser avec faster-whisper + silero-vad pour le streaming. Alternative à faster-whisper Large v3 quand le budget GPU est contraint.",
    digiDoubleAxis: "Phase 1 MVP — ASR souverain léger",
    benchmarkRef: "OpenAI Whisper Turbo release notes, Oct 2024",
  },
  {
    id: "audiogami",
    name: "Audiogami (Gamilab)",
    category: "open-source",
    tagline: "Swiss-hosted Whisper variant — production-ready, DigiDouble Phase 1",
    homepageUrl: "https://gamilab.com",
    docsUrl: "https://gamilab.com",
    wer: 3.5,
    werNote: "~3.5% WER estimated (based on Whisper Large v3 with Swiss-specific fine-tuning). French/German optimized.",
    latencyMs: 200,
    latencyMsTypical: 400,
    architecture: "Whisper Large v3 + Swiss-specific fine-tuning (Gamilab proprietary)",
    params: "1.5B (Whisper base)",
    license: "Proprietary (Gamilab)",
    selfHostable: true,
    selfHostNote: "Swiss-hosted (Exoscale). Full data sovereignty. Production deployment by Gamilab.",
    pricePerHour: 0,
    pricePerMin: 0,
    priceNote: "Included in Gamilab partnership. No per-use pricing for DigiDouble.",
    freeTier: "Partnership-based",
    streaming: true,
    streamingDetail: "Production streaming deployment. Swiss-hosted on Exoscale. French/German/Swiss German optimized.",
    multilingual: true,
    languages: 10,
    speakerDiarization: false,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: true,
    onPremise: true,
    onPremiseDetail: "Swiss-hosted (Exoscale). Full Swiss data sovereignty. GDPR + nLPD compliant.",
    gdprCompliant: true,
    dataResidency: "Switzerland (Exoscale). Full nLPD compliance.",
    score: { accuracy: 8, latency: 6, multilingual: 5, sovereignty: 10, pricing: 10, streaming: 8 },
    description: "Audiogami is Gamilab's production ASR service, based on Whisper Large v3 with Swiss-specific optimizations. Already deployed for DigiDouble Phase 1. Swiss-hosted on Exoscale with full nLPD/GDPR compliance. French, German, and Swiss German optimized. The primary ASR component for DigiDouble MVP.",
    descriptionFr: "Audiogami est le service ASR de production de Gamilab, basé sur Whisper Large v3 avec des optimisations spécifiques suisses. Déjà déployé pour la Phase 1 DigiDouble. Hébergé en Suisse sur Exoscale avec conformité nLPD/RGPD complète. Optimisé pour le français, l'allemand et le suisse-allemand. Le composant ASR principal du MVP DigiDouble.",
    strengths: ["Swiss sovereignty (Exoscale)", "nLPD + GDPR compliant", "French/German/Swiss German optimized", "Already in production for DigiDouble", "Partnership pricing (included)"],
    strengthsFr: ["Souveraineté suisse (Exoscale)", "Conformité nLPD + RGPD", "Optimisé français/allemand/suisse-allemand", "Déjà en production pour DigiDouble", "Tarification partenariat (inclus)"],
    weaknesses: ["Proprietary Gamilab service", "Limited language coverage (10)", "200ms latency (vs 75ms Deepgram)", "No public documentation"],
    weaknessesFr: ["Service propriétaire Gamilab", "Couverture linguistique limitée (10)", "200ms latence (vs 75ms Deepgram)", "Pas de documentation publique"],
    digiDoubleRelevance: "PRIMARY ASR for DigiDouble Phase 1 MVP. Already in production. Swiss sovereignty + French/German optimization = perfect fit. Benchmark against Deepgram Nova-3 to quantify latency trade-off (200ms vs 75ms). Consider faster-whisper as sovereign fallback.",
    digiDoubleRelevanceFr: "ASR PRINCIPAL pour le MVP Phase 1 DigiDouble. Déjà en production. Souveraineté suisse + optimisation français/allemand = parfaitement adapté. Benchmarker contre Deepgram Nova-3 pour quantifier le compromis latence (200ms vs 75ms). Considérer faster-whisper comme fallback souverain.",
    digiDoubleAxis: "Phase 1 MVP — ASR principal",
    benchmarkRef: "Gamilab production deployment, 2025",
  },
  {
    id: "voxtral-asr",
    name: "Voxtral ASR (Mistral)",
    category: "open-source",
    tagline: "European open-weights ASR — French/German native, Mistral ecosystem",
    homepageUrl: "https://mistral.ai",
    docsUrl: "https://docs.mistral.ai",
    wer: 5.0,
    werNote: "~5% WER estimated on French/German (announced March 2026, benchmarks pending).",
    latencyMs: 120,
    latencyMsTypical: 250,
    architecture: "Mistral multimodal (speech encoder + LLM decoder, open-weights)",
    params: "~7B estimated",
    license: "Apache 2.0 (open-weights)",
    selfHostable: true,
    selfHostNote: "Open-weights, self-hostable. EU-origin model. Mistral API also available.",
    pricePerHour: 0,
    pricePerMin: 0.003,
    priceNote: "Self-hosted: free. Mistral API: ~$0.003/min (estimated). Open-weights for sovereign deployment.",
    freeTier: "Open-weights — free self-hosted",
    streaming: true,
    streamingDetail: "Streaming-capable (announced). Part of Voxtral full-stack (ASR + TTS). 120ms estimated latency.",
    multilingual: true,
    languages: 30,
    speakerDiarization: false,
    wordTimestamps: true,
    punctuation: true,
    customVocabulary: false,
    onPremise: true,
    onPremiseDetail: "Open-weights — full on-premise. EU-origin (French company).",
    gdprCompliant: true,
    dataResidency: "EU (Mistral, France). Full control if self-hosted.",
    score: { accuracy: 7, latency: 8, multilingual: 6, sovereignty: 9, pricing: 9, streaming: 7 },
    description: "Voxtral ASR is Mistral's open-weights speech recognition model (announced March 2026). Part of the Voxtral full-stack (ASR + TTS). European open-weights with native French/German support. Creates a potential full-stack sovereign pipeline: Voxtral ASR → Mistral LLM → Voxtral TTS. Very new — production testing required.",
    descriptionFr: "Voxtral ASR est le modèle de reconnaissance vocale open-weights de Mistral (annoncé mars 2026). Fait partie du stack complet Voxtral (ASR + TTS). Open-weights européen avec support natif français/allemand. Crée un pipeline souverain full-stack potentiel : Voxtral ASR → Mistral LLM → Voxtral TTS. Très récent — tests production requis.",
    strengths: ["European open-weights (Apache 2.0)", "Native French/German support", "Full-stack Mistral ecosystem (ASR+LLM+TTS)", "Self-hostable — full sovereignty", "~120ms estimated latency"],
    strengthsFr: ["Open-weights européen (Apache 2.0)", "Support natif français/allemand", "Écosystème Mistral full-stack (ASR+LLM+TTS)", "Self-hostable — souveraineté totale", "~120ms latence estimée"],
    weaknesses: ["Very new (March 2026) — no production track record", "Benchmarks pending", "~7B params — significant GPU requirement", "No speaker diarization"],
    weaknessesFr: ["Très récent (mars 2026) — pas de track record production", "Benchmarks en attente", "~7B params — GPU significatif requis", "Pas de diarisation"],
    digiDoubleRelevance: "High priority evaluation for Phase 1 MVP. Creates full-stack sovereign pipeline with Voxtral TTS + Mistral LLM. French/German native support critical for Swiss market. Very new — needs 3-month production testing before Phase 1 deployment.",
    digiDoubleRelevanceFr: "Évaluation haute priorité pour le MVP Phase 1. Crée un pipeline souverain full-stack avec Voxtral TTS + Mistral LLM. Support natif français/allemand critique pour le marché suisse. Très récent — 3 mois de tests production requis avant déploiement Phase 1.",
    digiDoubleAxis: "Phase 1 MVP — Stack Mistral souverain",
    benchmarkRef: "Mistral AI announcement, Mar 26, 2026",
  },
];

export function getSTTData(): STTData[] {
  return sttDatabase;
}

export function getSTTById(id: string): STTData | undefined {
  return sttDatabase.find((s) => s.id === id);
}

export function getSTTByCategory(category: STTCategory): STTData[] {
  return sttDatabase.filter((s) => s.category === category);
}
