// ============================================================
// ttsData.ts — GamiWays Research Portal
// Données centralisées TTS & Voice-to-Voice (2025–2026)
// Sources : Artificial Analysis, Inworld benchmark, docs officiels
// ============================================================

export type TTSCategory = "cloud-api" | "open-source";

export interface TTSScore {
  quality: number;       // 1–10 (basé ELO normalisé)
  latency: number;       // 1–10 (10 = <50ms, 1 = >1s)
  voiceCloning: number;  // 1–10
  expressiveness: number;// 1–10
  sovereignty: number;   // 1–10 (10 = full self-hosted)
  pricing: number;       // 1–10 (10 = gratuit/très bon marché)
  multilingual: number;  // 1–10
}

export interface TTSData {
  id: string;
  name: string;
  category: TTSCategory;
  tagline: string;
  homepageUrl: string;
  docsUrl: string;
  // Specs techniques
  ttfaMs: number;           // Time to First Audio en ms (best case)
  ttfaMsTypical: number;    // TTFA typique
  architecture: string;     // ex: "State Space Model", "LLM-based", "Flow matching"
  params: string;           // ex: "82M", "3B", "N/A (cloud)"
  license: string;          // ex: "Apache 2.0", "MIT", "Commercial"
  selfHostable: boolean;
  selfHostNote: string;
  // Pricing
  pricePerMChar: number;    // $ par million de caractères
  pricePerMin: number;      // $ par minute (calculé)
  priceNote: string;
  freeTier: string;
  // Qualité
  eloScore: number;         // Artificial Analysis ELO (0 si non disponible)
  eloRank: number;          // Rang sur leaderboard (0 si non disponible)
  // Capacités
  voiceCloning: boolean;
  voiceCloningDetail: string;
  streaming: boolean;
  streamingDetail: string;
  multilingual: boolean;
  languages: number;
  emotionControl: boolean;
  emotionDetail: string;
  lipsyncData: boolean;     // fournit timestamps/visèmes pour lip-sync
  lipsyncDetail: string;
  // Souveraineté
  onPremise: boolean;
  onPremiseDetail: string;
  gdprCompliant: boolean;
  dataResidency: string;
  // Scores comparatifs
  score: TTSScore;
  // Description
  description: string;
  descriptionFr: string;
  strengths: string[];
  strengthsFr: string[];
  weaknesses: string[];
  weaknessesFr: string[];
  // Pertinence GamiWays
  digiDoubleRelevance: string;
  digiDoubleRelevanceFr: string;
  digiDoubleAxis: string;   // ex: "Phase 1 MVP", "Axe 2a", "Référence"
  // Références
  arxivRef?: string;
  benchmarkRef?: string;
  // Traçabilité des données
  dataUpdatedAt: string;      // ISO date de la dernière mise à jour des chiffres (YYYY-MM-DD)
  dataUpdateNote: string;     // Contexte de la mise à jour
  sources: Array<{ label: string; url: string; type: "pricing" | "benchmark" | "docs" | "news" }>;
}

const ttsDatabase: TTSData[] = [
  // ─── CLOUD API ───────────────────────────────────────────────
  {
    id: "elevenlabs",
    name: "ElevenLabs v3",
    category: "cloud-api",
    tagline: "Industry reference — 380+ voices, 70+ languages, emotional range",
    homepageUrl: "https://elevenlabs.io",
    docsUrl: "https://elevenlabs.io/docs",
    ttfaMs: 75,
    ttfaMsTypical: 200,
    architecture: "Transformer (proprietary)",
    params: "N/A (cloud)",
    license: "Commercial",
    selfHostable: false,
    selfHostNote: "Cloud only. Enterprise VPC option available.",
    pricePerMChar: 206,
    pricePerMin: 0.206,
    priceNote: "Multilingual v3: $206/1M chars. Flash v2.5: ~$75/1M chars. Conversational AI: $0.08/min (Business).",
    freeTier: "20,000 chars/month (non-commercial)",
    eloScore: 1178,
    eloRank: 4,
    voiceCloning: true,
    voiceCloningDetail: "Zero-shot (instant) + professional fine-tuning. 30+ min audio for pro cloning. 380+ pre-built voices.",
    streaming: true,
    streamingDetail: "WebSocket streaming. Flash v2.5: 75ms inference latency. Turbo v2.5: 32ms inference.",
    multilingual: true,
    languages: 70,
    emotionControl: true,
    emotionDetail: "SSML + audio markup tags. Emotional range rated best-in-class for content production.",
    lipsyncData: true,
    lipsyncDetail: "Word-level timestamps via Alignment API. Phoneme-level available.",
    onPremise: false,
    onPremiseDetail: "No on-premise. Enterprise VPC available on request.",
    gdprCompliant: true,
    dataResidency: "US (default). EU data residency on enterprise plan.",
    score: { quality: 9, latency: 8, voiceCloning: 10, expressiveness: 10, sovereignty: 2, pricing: 2, multilingual: 10 },
    description: "ElevenLabs is the industry reference for voice quality and breadth. ELO 1178 (rank #4 Artificial Analysis, May 2026). Flash v2.5 achieves 75ms inference latency. Best-in-class for content production requiring emotional range across 70+ languages. 20.6× more expensive than Inworld at scale.",
    descriptionFr: "ElevenLabs est la référence industrie pour la qualité vocale. ELO 1178 (rang #4 Artificial Analysis, mai 2026). Flash v2.5 atteint 75ms de latence d'inférence. Meilleure solution pour la production de contenu nécessitant une gamme émotionnelle étendue sur 70+ langues. 20,6× plus cher qu'Inworld à l'échelle.",
    strengths: ["ELO 1178 — top 4 quality", "380+ voices, 70+ languages", "Zero-shot + pro voice cloning", "75ms inference (Flash v2.5)", "Word-level timestamps for lip-sync", "Extensive SSML + emotion tags"],
    strengthsFr: ["ELO 1178 — top 4 qualité", "380+ voix, 70+ langues", "Clonage voix zero-shot + pro", "75ms inférence (Flash v2.5)", "Timestamps mot-à-mot pour lip-sync", "SSML + tags émotion étendus"],
    weaknesses: ["$206/1M chars — 20.6× more expensive than Inworld", "Cloud only, no sovereignty", "Not optimized for real-time agents (vs Cartesia)", "No on-premise option"],
    weaknessesFr: ["$206/1M chars — 20,6× plus cher qu'Inworld", "Cloud uniquement, pas de souveraineté", "Non optimisé pour agents temps réel (vs Cartesia)", "Pas d'option on-premise"],
    digiDoubleRelevance: "Quality reference for validation phases. Voice cloning capability critical for GamiWays Phase 1 MVP (voice-to-voice). Too expensive for production scale. Evaluate Flash v2.5 ($75/1M) for prototype.",
    digiDoubleRelevanceFr: "Référence qualité pour les phases de validation. Clonage vocal critique pour le MVP Phase 1 (voice-to-voice). Trop cher pour la production à l'échelle. Évaluer Flash v2.5 ($75/1M) pour le prototype.",
    digiDoubleAxis: "Phase 1 MVP — Référence qualité",
    benchmarkRef: "Artificial Analysis Speech Leaderboard, Jan 2026",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Eleven v3 ELO 1178 (rank #4, May 2026, Artificial Analysis Arena). Flash v2.5 TTFA 75ms confirmed. Pricing: $206/1M chars (v3), $75/1M (Flash v2.5). Enterprise on-premise available.",
    sources: [
      { label: "ElevenLabs Pricing", url: "https://elevenlabs.io/pricing", type: "pricing" },
      { label: "ElevenLabs Docs", url: "https://elevenlabs.io/docs", type: "docs" },
      { label: "Artificial Analysis TTS Leaderboard", url: "https://artificialanalysis.ai/text-to-speech", type: "benchmark" },
      { label: "ElevenLabs Flash v2.5 Release", url: "https://elevenlabs.io/blog/flash-v2-5", type: "news" },
    ],
  },
  {
    id: "cartesia",
    name: "Cartesia Sonic 3",
    category: "cloud-api",
    tagline: "Fastest TTFA on the market — 40ms, State Space Model architecture",
    homepageUrl: "https://cartesia.ai",
    docsUrl: "https://docs.cartesia.ai",
    ttfaMs: 40,
    ttfaMsTypical: 90,
    architecture: "State Space Model (SSM) — linear scaling vs quadratic transformers",
    params: "N/A (cloud)",
    license: "Commercial",
    selfHostable: false,
    selfHostNote: "Cloud API only. WebSocket multiplexing for concurrent streams.",
    pricePerMChar: 46.70,
    pricePerMin: 0.047,
    priceNote: "$46.70/1M chars. Pro: $5/month + 100K credits. Free: 10K credits.",
    freeTier: "10,000 credits (no commercial use)",
    eloScore: 1069,
    eloRank: 8,
    voiceCloning: true,
    voiceCloningDetail: "Instant cloning from 3 seconds of audio. 40+ languages. Fine-grained emotion, volume, speed controls.",
    streaming: true,
    streamingDetail: "40ms TTFA — industry's lowest. WebSocket multiplexing for dozens of concurrent streams. 2× faster inference than transformers.",
    multilingual: true,
    languages: 40,
    emotionControl: true,
    emotionDetail: "Fine-grained emotion, volume, speed controls. Emotion tags in API.",
    lipsyncData: false,
    lipsyncDetail: "No native viseme/timestamp output. Requires external alignment.",
    onPremise: false,
    onPremiseDetail: "Cloud only.",
    gdprCompliant: true,
    dataResidency: "US",
    score: { quality: 7, latency: 10, voiceCloning: 8, expressiveness: 7, sovereignty: 2, pricing: 5, multilingual: 7 },
    description: "Cartesia Sonic 3 holds the industry record for TTFA at 40ms, 4× faster than the next alternative. State Space Model architecture scales linearly (vs quadratic transformers), enabling 2× faster inference and 4× higher throughput. ELO 1069 (rank #8, May 2026). Best choice when minimum latency is the primary requirement for voice agents.",
    descriptionFr: "Cartesia Sonic 3 détient le record industrie de TTFA à 40ms, 4× plus rapide que l'alternative suivante. Architecture State Space Model à scaling linéaire (vs transformers quadratiques), 2× plus rapide en inférence et 4× plus de débit. ELO 1069 (rang #8, mai 2026). Meilleur choix quand la latence minimale est la priorité pour les agents vocaux.",
    strengths: ["40ms TTFA — industry record", "SSM: 2× faster inference, 4× throughput vs transformers", "3-second voice cloning", "WebSocket multiplexing", "40+ languages"],
    strengthsFr: ["40ms TTFA — record industrie", "SSM: 2× inférence, 4× débit vs transformers", "Clonage voix en 3 secondes", "Multiplexage WebSocket", "40+ langues"],
    weaknesses: ["ELO 1069 — 91 points below Inworld", "500-char limit on Sonic Turbo", "No lip-sync timestamps", "Cloud only"],
    weaknessesFr: ["ELO 1069 — 91 points sous Inworld", "Limite 500 chars sur Sonic Turbo", "Pas de timestamps lip-sync", "Cloud uniquement"],
    digiDoubleRelevance: "Primary candidate for Phase 1 MVP voice-to-voice pipeline. 40ms TTFA is critical for sub-2s end-to-end latency target. SSM architecture worth studying for sovereign implementation (Axis 1 R&D).",
    digiDoubleRelevanceFr: "Candidat principal pour le pipeline voice-to-voice du MVP Phase 1. 40ms TTFA critique pour l'objectif <2s end-to-end. Architecture SSM à étudier pour l'implémentation souveraine (Axe 1 R&D).",
    digiDoubleAxis: "Phase 1 MVP — Latence critique",
    benchmarkRef: "Cartesia docs + Artificial Analysis, Jan 2026",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Sonic 3 ELO 1069 (rank #8, May 2026, Artificial Analysis Arena). TTFA 90ms (Sonic 3), 40ms (Sonic 2 Turbo). Pricing: $46.70/1M chars. GDPR + EU data residency confirmed.",
    sources: [
      { label: "Cartesia Pricing", url: "https://cartesia.ai/pricing", type: "pricing" },
      { label: "Cartesia Docs", url: "https://docs.cartesia.ai", type: "docs" },
      { label: "Artificial Analysis TTS", url: "https://artificialanalysis.ai/text-to-speech", type: "benchmark" },
      { label: "Cartesia Sonic 3 Release", url: "https://cartesia.ai/blog/sonic-3", type: "news" },
    ],
  },
  {
    id: "inworld_tts",
    name: "Inworld TTS-2 + Realtime API",
    category: "cloud-api",
    tagline: "#1 Artificial Analysis Arena — TTS-2 (research preview) : Voice Direction, Conversational Awareness, 100+ langues",
    homepageUrl: "https://inworld.ai",
    docsUrl: "https://docs.inworld.ai/docs/tutorial-basics/text-to-speech/",
    ttfaMs: 130,
    ttfaMsTypical: 250,
    architecture: "SpeechLM (streaming-native, quantization-aware) — TTS-2 rebuilt for realtime conversation",
    params: "N/A (cloud)",
    license: "Commercial (training framework open-sourced)",
    selfHostable: true,
    selfHostNote: "On-premise deployment available on Enterprise plan only. EU + India data residency. Custom model weights access.",
    pricePerMChar: 35,
    pricePerMin: 0.035,
    priceNote: "TTS-2 & TTS-1.5 Max: $35/1M chars ($0.035/min) On-Demand. TTS-1.5 Mini: $25/1M chars ($0.025/min). Developer plan: TTS-2 at $30/1M. Growth plan: TTS-2 at $25/1M. Enterprise: as low as $10/1M (TTS-2 & Max), $5/1M (Mini). Free tier: up to 40 min TTS included.",
    freeTier: "Up to 40 min TTS included on On-Demand (free)",
    eloScore: 1160,
    eloRank: 1,
    voiceCloning: true,
    voiceCloningDetail: "Instant voice cloning (free). Professional voice cloning (Growth/Enterprise add-on). Advanced Voice Design: create a voice from a prose description — no reference audio needed. Up to 5 custom voices (On-Demand), 100 (Creator), 1,000 (Developer), 3,000 (Growth). ElevenLabs migration tool available.",
    streaming: true,
    streamingDetail: "Streaming-native via WebSocket and REST. Sub-200ms median TTFA for TTS alone. Realtime API: full-duplex WebSocket speech-to-speech with turn detection, tool calling mid-session, provider-agnostic LLM routing (220+ models). Backchannel fillers stream in parallel during LLM reasoning. Partial responses reach user before full sentence is composed.",
    multilingual: true,
    languages: 100,
    emotionControl: true,
    emotionDetail: "TTS-2 Voice Direction: natural language delivery instructions inline (e.g. [speak sadly, as if something bad just happened]). Inline non-verbals: [laugh], [sigh], [breathe], [clear_throat], [cough]. Conversational Awareness: model hears prior audio turns — tone, pacing, emotional state carry forward automatically. Word/char/phoneme/viseme timestamps.",
    lipsyncData: true,
    lipsyncDetail: "Word, character, phoneme, and viseme-level timestamps. Unity/Unreal SDKs with lipsync templates.",
    onPremise: true,
    onPremiseDetail: "On-premise deployment available on Enterprise plan. EU + India data residency. SOC2 Type II, GDPR, HIPAA, ZDR, BAA compliant.",
    gdprCompliant: true,
    dataResidency: "US, EU, India",
    score: { quality: 10, latency: 8, voiceCloning: 9, expressiveness: 10, sovereignty: 6, pricing: 7, multilingual: 10 },
    description: "Inworld TTS-2 (research preview, May 2026) is a new generation voice model built for realtime conversation. TTS 1.5 already ranks #1 on Artificial Analysis Speech Arena (ahead of Google and ElevenLabs). TTS-2 adds four capabilities: Voice Direction (natural language delivery instructions), Conversational Awareness (model hears prior audio turns), Crosslingual (one voice identity across 100+ languages, mid-utterance switching), and Advanced Voice Design (voice from prose description). Pricing: $0.035/min On-Demand (same as TTS 1.5 Max). Full platform: TTS + STT (inworld-stt-1) + Realtime API (WebSocket S2S, tool calling) + LLM Router (220+ models). On-premise on Enterprise. Integrations: Cloudflare, DeepInfra, LiveKit, Stream, VoiceRun.",
    descriptionFr: "Inworld TTS-2 (research preview, mai 2026) est une nouvelle génération de modèle vocal construite pour la conversation en temps réel. TTS 1.5 est déjà #1 sur l'Artificial Analysis Speech Arena (devant Google et ElevenLabs). TTS-2 ajoute quatre capacités : Voice Direction (instructions de délivrance en langage naturel), Conversational Awareness (le modèle entend les tours audio précédents), Crosslingual (une identité vocale sur 100+ langues, switch mid-phrase), et Advanced Voice Design (voix à partir d'une description en prose). Prix : 0,035$/min On-Demand (même tarif que TTS 1.5 Max). Plateforme complète : TTS + STT + Realtime API (WebSocket S2S, tool calling) + LLM Router (220+ modèles). On-premise sur Enterprise.",
    strengths: ["TTS 1.5 #1 Artificial Analysis Speech Arena (devant Google, ElevenLabs)", "TTS-2 : Voice Direction — instructions de livraison en langage naturel", "TTS-2 : Conversational Awareness — entend les tours audio précédents", "TTS-2 : 100+ langues, switch mid-phrase, une seule identité vocale", "TTS-2 : Advanced Voice Design — voix depuis description en prose", "Plateforme complète : TTS + STT + Realtime S2S + LLM Router (220+ modèles)", "Sub-200ms median TTFA (TTS seul)", "Viseme timestamps pour avatar lip-sync", "On-premise sur Enterprise (GDPR, HIPAA, ZDR, SOC2 Type II)"],
    strengthsFr: ["TTS 1.5 #1 Artificial Analysis Speech Arena (devant Google, ElevenLabs)", "TTS-2 : Voice Direction — instructions de livraison en langage naturel", "TTS-2 : Conversational Awareness — entend les tours audio précédents", "TTS-2 : 100+ langues, switch mid-phrase, une seule identité vocale", "TTS-2 : Advanced Voice Design — voix depuis description en prose", "Plateforme complète : TTS + STT + Realtime S2S + LLM Router (220+ modèles)", "Sub-200ms median TTFA (TTS seul)", "Timestamps visèmes pour lip-sync avatar", "On-premise sur Enterprise (RGPD, HIPAA, ZDR, SOC2 Type II)"],
    weaknesses: ["TTS-2 en research preview (pas encore GA)", "On-premise uniquement sur Enterprise (tarif custom)", "Prix On-Demand TTS-2 = $0.035/min (3.5× plus cher que TTS-1.5 Mini)", "LLM Router model list changes frequently"],
    weaknessesFr: ["TTS-2 en research preview (pas encore GA)", "On-premise uniquement sur Enterprise (tarif custom)", "Prix On-Demand TTS-2 = 0,035$/min (3,5× plus cher que TTS-1.5 Mini)", "Liste modèles LLM Router change fréquemment"],
    digiDoubleAxis: "Phase 1 MVP — Qualité + Pipeline conversationnel complet + 100+ langues",
    benchmarkRef: "Artificial Analysis Speech Arena (TTS 1.5 #1, May 2026). TTS-2 research preview announced May 5, 2026.",
    digiDoubleRelevance: "Top candidate for GamiWays pipeline. TTS-2 Conversational Awareness directly addresses the challenge of emotionally coherent multi-turn avatars. Voice Direction enables per-scene delivery control without re-recording. 100+ crosslingual support covers all target markets. Viseme timestamps directly usable for avatar lip-sync. On-premise on Enterprise aligns with sovereignty requirements.",
    digiDoubleRelevanceFr: "Candidat principal pour le pipeline GamiWays. TTS-2 Conversational Awareness répond directement au défi des avatars multi-tours émotionnellement cohérents. Voice Direction permet le contrôle de la livraison par scène sans reenregistrement. 100+ langues couvre tous les marchés cibles. Timestamps visèmes directement utilisables pour le lip-sync avatar. On-premise sur Enterprise aligné avec les exigences de souveraineté.",
    dataUpdatedAt: "2026-05-06",
    dataUpdateNote: "TTS-2 research preview launched May 5, 2026. 4 new capabilities: Voice Direction, Conversational Awareness, Crosslingual (100+ langs), Advanced Voice Design. Pricing: $0.035/min On-Demand (same as TTS 1.5 Max). TTS 1.5 Max/Mini still available. On-premise Enterprise only.",
    sources: [
      { label: "Inworld TTS-2 Announcement", url: "https://inworld.ai/blog/realtime-tts-2", type: "benchmark" },
      { label: "Inworld Pricing", url: "https://inworld.ai/pricing", type: "pricing" },
      { label: "Inworld TTS Docs", url: "https://docs.inworld.ai/docs/tutorial-basics/text-to-speech/", type: "docs" },
      { label: "Artificial Analysis TTS Arena", url: "https://artificialanalysis.ai/text-to-speech", type: "benchmark" },
      { label: "Inworld Realtime API", url: "https://inworld.ai/realtime-api", type: "docs" },
    ],
  },
  {
    id: "hume_octave",
    name: "Hume AI Octave 2",
    category: "cloud-api",
    tagline: "LLM-based emotional TTS — natural language emotion control",
    homepageUrl: "https://hume.ai",
    docsUrl: "https://dev.hume.ai/docs",
    ttfaMs: 100,
    ttfaMsTypical: 200,
    architecture: "LLM-based (understands emotional context)",
    params: "N/A (cloud)",
    license: "Commercial",
    selfHostable: false,
    selfHostNote: "Cloud only. EVI 3 speech-to-speech under 300ms.",
    pricePerMChar: 7.60,
    pricePerMin: 0.0076,
    priceNote: "$7.60/1M chars. Starter: $3/month + 30K chars. Business: $500/month + 10M chars.",
    freeTier: "10,000 chars/month",
    eloScore: 1046,
    eloRank: 14,
    voiceCloning: true,
    voiceCloningDetail: "Voice cloning from 15 seconds of audio.",
    streaming: true,
    streamingDetail: "~100ms latency (200ms TTFT with streaming). EVI 3: speech-to-speech under 300ms.",
    multilingual: true,
    languages: 11,
    emotionControl: true,
    emotionDetail: "Natural language emotion control: 'sound sarcastic', 'whisper fearfully'. LLM understands emotional context without SSML tags.",
    lipsyncData: false,
    lipsyncDetail: "No native lip-sync data.",
    onPremise: false,
    onPremiseDetail: "Cloud only.",
    gdprCompliant: true,
    dataResidency: "US",
    score: { quality: 7, latency: 8, voiceCloning: 6, expressiveness: 10, sovereignty: 2, pricing: 8, multilingual: 4 },
    description: "Hume Octave 2 is the first TTS built on LLM intelligence that understands emotional context. Natural language instructions ('sound sarcastic', 'whisper fearfully') replace manual SSML tags. EVI 3 enables speech-to-speech responses under 300ms. Cheapest among top-15 providers at $7.60/1M chars.",
    descriptionFr: "Hume Octave 2 est le premier TTS basé sur l'intelligence LLM qui comprend le contexte émotionnel. Les instructions en langage naturel ('parle de manière sarcastique', 'chuchote avec peur') remplacent les tags SSML manuels. EVI 3 permet des réponses speech-to-speech en moins de 300ms. Le moins cher parmi les 15 premiers à $7,60/1M chars.",
    strengths: ["Natural language emotion control", "EVI 3: speech-to-speech <300ms", "$7.60/1M — cheapest top-15", "LLM-based contextual understanding"],
    strengthsFr: ["Contrôle émotion en langage naturel", "EVI 3 : speech-to-speech <300ms", "$7,60/1M — moins cher top-15", "Compréhension contextuelle LLM"],
    weaknesses: ["ELO 1046 — rank #14", "Only 11 languages", "Cloud only, no sovereignty"],
    weaknessesFr: ["ELO 1046 — rang #14", "Seulement 11 langues", "Cloud uniquement, pas de souveraineté"],
    digiDoubleRelevance: "Interesting for Phase 1 MVP due to natural language emotion control and low cost. EVI 3 speech-to-speech pipeline worth evaluating. Limited language support (11) may be an issue for multilingual use cases.",
    digiDoubleRelevanceFr: "Intéressant pour le MVP Phase 1 grâce au contrôle émotion en langage naturel et au faible coût. Pipeline speech-to-speech EVI 3 à évaluer. Support limité à 11 langues potentiellement problématique pour les cas d'usage multilingues.",
    digiDoubleAxis: "Phase 1 MVP — Expressivité émotionnelle",
    benchmarkRef: "Artificial Analysis Speech Leaderboard, Jan 2026",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Hume Octave 2 ELO 1160 (rank #2, Apr 2026). Pricing: $0.06/min (Octave 2). EVI 3 speech-to-speech <300ms. 11 languages confirmed.",
    sources: [
      { label: "Hume AI Pricing", url: "https://www.hume.ai/pricing", type: "pricing" },
      { label: "Hume AI Docs", url: "https://dev.hume.ai/docs", type: "docs" },
      { label: "Artificial Analysis TTS", url: "https://artificialanalysis.ai/text-to-speech", type: "benchmark" },
    ],
  },
  {
    id: "fish_audio",
    name: "Fish Audio OpenAudio S1",
    category: "cloud-api",
    tagline: "Pay-as-you-go voice cloning — 70% cheaper than ElevenLabs",
    homepageUrl: "https://fish.audio",
    docsUrl: "https://docs.fish.audio",
    ttfaMs: 200,
    ttfaMsTypical: 400,
    architecture: "Flow matching (proprietary)",
    params: "N/A (cloud)",
    license: "Commercial",
    selfHostable: false,
    selfHostNote: "Cloud API. S1-mini open-source weights available for self-hosting.",
    pricePerMChar: 15,
    pricePerMin: 0.015,
    priceNote: "$15/1M chars. Pay-as-you-go, no subscription. Voice cloning included at same price.",
    freeTier: "Limited free tier",
    eloScore: 1128,
    eloRank: 6,
    voiceCloning: true,
    voiceCloningDetail: "Voice cloning included at no extra cost. 10-second audio sample. 70% cheaper than ElevenLabs for equivalent quality.",
    streaming: true,
    streamingDetail: "Streaming API available. ~200ms TTFA.",
    multilingual: true,
    languages: 13,
    emotionControl: true,
    emotionDetail: "Emotion control via API parameters. Expressive synthesis.",
    lipsyncData: false,
    lipsyncDetail: "No native lip-sync timestamps.",
    onPremise: false,
    onPremiseDetail: "Cloud API. S1-mini weights available for self-hosting.",
    gdprCompliant: true,
    dataResidency: "US/Asia",
    score: { quality: 7, latency: 6, voiceCloning: 8, expressiveness: 7, sovereignty: 4, pricing: 7, multilingual: 5 },
    description: "Fish Audio OpenAudio S1 ranks #6 on Artificial Analysis (ELO 1128, May 2026). Voice cloning included at the same price as basic TTS — no extra fees. 70% cheaper than ElevenLabs. S1-mini open-source weights enable self-hosting for sovereign deployments.",
    descriptionFr: "Fish Audio OpenAudio S1 est classé #6 sur Artificial Analysis (ELO 1128, mai 2026). Clonage vocal inclus au même prix que le TTS de base — sans frais supplémentaires. 70% moins cher qu'ElevenLabs. Les poids open-source de S1-mini permettent l'auto-hébergement pour les déploiements souverains.",
    strengths: ["ELO 1128 — rank #6", "Voice cloning included at no extra cost", "70% cheaper than ElevenLabs", "S1-mini open-source for self-hosting", "13 languages"],
    strengthsFr: ["ELO 1128 — rang #6", "Clonage vocal inclus sans frais", "70% moins cher qu'ElevenLabs", "S1-mini open-source pour auto-hébergement", "13 langues"],
    weaknesses: ["~200ms TTFA (slower than Cartesia)", "No native lip-sync data", "Limited documentation"],
    weaknessesFr: ["~200ms TTFA (plus lent que Cartesia)", "Pas de données lip-sync natives", "Documentation limitée"],
    digiDoubleRelevance: "Good cost/quality ratio for Phase 1 MVP. S1-mini self-hosting option aligns with sovereignty requirements. Voice cloning included without extra cost is a significant advantage.",
    digiDoubleRelevanceFr: "Bon rapport coût/qualité pour le MVP Phase 1. Option auto-hébergement S1-mini alignée avec les exigences de souveraineté. Clonage vocal inclus sans frais supplémentaires est un avantage significatif.",
    digiDoubleAxis: "Phase 1 MVP — Coût/Souveraineté",
    benchmarkRef: "Artificial Analysis Speech Leaderboard + Fish Audio docs, 2026",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Fish Audio OpenAudio S1 ELO 1128 (rank #6, May 2026). Pricing: $15/1M chars. S1-mini open-source for self-hosting. 13 languages.",
    sources: [
      { label: "Fish Audio Website", url: "https://fish.audio", type: "docs" },
      { label: "Fish Audio Pricing", url: "https://fish.audio/pricing", type: "pricing" },
      { label: "Artificial Analysis TTS", url: "https://artificialanalysis.ai/text-to-speech", type: "benchmark" },
      { label: "Fish Audio GitHub", url: "https://github.com/fishaudio/fish-speech", type: "docs" },
    ],
  },
  {
    id: "deepgram_aura",
    name: "Deepgram Aura 2",
    category: "cloud-api",
    tagline: "Ultra-low latency TTS optimized for voice agents — <100ms",
    homepageUrl: "https://deepgram.com",
    docsUrl: "https://developers.deepgram.com/docs/tts-models",
    ttfaMs: 80,
    ttfaMsTypical: 150,
    architecture: "Proprietary streaming neural TTS",
    params: "N/A (cloud)",
    license: "Commercial",
    selfHostable: false,
    selfHostNote: "Cloud only. On-premise via enterprise agreement.",
    pricePerMChar: 15,
    pricePerMin: 0.015,
    priceNote: "$15/1M chars. Often bundled with Deepgram ASR for full voice agent stack.",
    freeTier: "$200 free credits on signup",
    eloScore: 0,
    eloRank: 0,
    voiceCloning: false,
    voiceCloningDetail: "No voice cloning. Pre-built voices only.",
    streaming: true,
    streamingDetail: "<100ms TTFA. Optimized for real-time voice agents. Often paired with Deepgram Nova-3 ASR (75–200ms) for full stack.",
    multilingual: false,
    languages: 1,
    emotionControl: false,
    emotionDetail: "Limited emotion control. Focused on natural, neutral speech.",
    lipsyncData: false,
    lipsyncDetail: "No native lip-sync data.",
    onPremise: false,
    onPremiseDetail: "Cloud only. Enterprise on-premise via agreement.",
    gdprCompliant: true,
    dataResidency: "US, EU",
    score: { quality: 6, latency: 9, voiceCloning: 1, expressiveness: 4, sovereignty: 3, pricing: 7, multilingual: 1 },
    description: "Deepgram Aura 2 is optimized for voice agent pipelines, achieving <100ms TTFA. Best used in conjunction with Deepgram Nova-3 ASR (75–200ms) for a complete, low-latency ASR+TTS stack. No voice cloning, limited expressiveness — focused on speed and reliability for English voice agents.",
    descriptionFr: "Deepgram Aura 2 est optimisé pour les pipelines d'agents vocaux, atteignant <100ms de TTFA. Idéalement utilisé avec Deepgram Nova-3 ASR (75–200ms) pour un stack ASR+TTS complet et à faible latence. Pas de clonage vocal, expressivité limitée — focalisé sur la vitesse et la fiabilité pour les agents vocaux en anglais.",
    strengths: ["<100ms TTFA", "Optimized for voice agent pipelines", "Natural pairing with Deepgram ASR", "Reliable at scale"],
    strengthsFr: ["<100ms TTFA", "Optimisé pour pipelines agents vocaux", "Couplage naturel avec Deepgram ASR", "Fiable à l'échelle"],
    weaknesses: ["No voice cloning", "English only (Aura 2)", "Limited expressiveness", "No lip-sync data"],
    weaknessesFr: ["Pas de clonage vocal", "Anglais uniquement (Aura 2)", "Expressivité limitée", "Pas de données lip-sync"],
    digiDoubleRelevance: "Relevant for Phase 1 MVP if using Deepgram Nova-3 for ASR. The ASR+TTS stack from a single provider simplifies integration and reduces latency. Limited to English and no voice cloning are significant constraints.",
    digiDoubleRelevanceFr: "Pertinent pour le MVP Phase 1 si utilisation de Deepgram Nova-3 pour l'ASR. Le stack ASR+TTS d'un seul fournisseur simplifie l'intégration et réduit la latence. Limité à l'anglais et sans clonage vocal sont des contraintes significatives.",
    digiDoubleAxis: "Phase 1 MVP — Stack ASR+TTS intégré",
    benchmarkRef: "Deepgram docs + Introl Voice AI guide, Jan 2026",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Deepgram Aura-2 pricing: $15/1M chars. TTFA <100ms. English only. Best paired with Deepgram Nova-3 ASR for full voice agent stack.",
    sources: [
      { label: "Deepgram Aura-2 Pricing", url: "https://deepgram.com/pricing", type: "pricing" },
      { label: "Deepgram Aura-2 Docs", url: "https://developers.deepgram.com/docs/tts-models", type: "docs" },
      { label: "Artificial Analysis TTS", url: "https://artificialanalysis.ai/text-to-speech", type: "benchmark" },
    ],
  },

  // ─── OPEN-SOURCE / SELF-HOSTED ────────────────────────────────
  {
    id: "kokoro",
    name: "Kokoro 82M v1.0",
    category: "open-source",
    tagline: "Highest-ranked open-weight TTS — ELO 1059, 82M params, Apache 2.0",
    homepageUrl: "https://huggingface.co/hexgrad/Kokoro-82M",
    docsUrl: "https://github.com/hexgrad/kokoro",
    ttfaMs: 60,
    ttfaMsTypical: 120,
    architecture: "Lightweight transformer (82M params)",
    params: "82M",
    license: "Apache 2.0",
    selfHostable: true,
    selfHostNote: "Runs on CPU or modest GPU. Edge deployment possible. 36× real-time on T4 GPU.",
    pricePerMChar: 0.70,
    pricePerMin: 0.0007,
    priceNote: "$0.70/1M chars (managed inference). Self-hosted: near-zero marginal cost.",
    freeTier: "Free (open weights)",
    eloScore: 1059,
    eloRank: 9,
    voiceCloning: false,
    voiceCloningDetail: "No zero-shot voice cloning. Pre-built voices only (American/British English).",
    streaming: true,
    streamingDetail: "Streaming-capable. 36× real-time on T4 GPU. <100ms on modern hardware.",
    multilingual: false,
    languages: 2,
    emotionControl: false,
    emotionDetail: "Limited emotion control. Natural prosody but no explicit emotion tags.",
    lipsyncData: false,
    lipsyncDetail: "No native lip-sync data. Can be paired with external aligner.",
    onPremise: true,
    onPremiseDetail: "Full self-hosting. Apache 2.0 license. Runs on CPU without GPU.",
    gdprCompliant: true,
    dataResidency: "Fully local — no data leaves the server.",
    score: { quality: 7, latency: 9, voiceCloning: 1, expressiveness: 5, sovereignty: 10, pricing: 10, multilingual: 2 },
    description: "Kokoro 82M v1.0 is the highest-ranked open-weight TTS model on Artificial Analysis (ELO 1059, rank #9). At just 82M parameters, it runs efficiently on CPU or modest GPU with 36× real-time speed on T4. Apache 2.0 license enables full sovereign deployment. Best price-performance among open models: $0.70/1M chars managed.",
    descriptionFr: "Kokoro 82M v1.0 est le modèle TTS open-weight le mieux classé sur Artificial Analysis (ELO 1059, rang #9). Avec seulement 82M paramètres, il fonctionne efficacement sur CPU ou GPU modeste à 36× temps réel sur T4. Licence Apache 2.0 pour déploiement souverain complet. Meilleur rapport qualité/prix parmi les modèles ouverts : $0,70/1M chars en mode géré.",
    strengths: ["ELO 1059 — #1 open-weight model", "82M params — runs on CPU", "36× real-time on T4 GPU", "Apache 2.0 — full sovereignty", "$0.70/1M chars managed"],
    strengthsFr: ["ELO 1059 — #1 modèle open-weight", "82M params — fonctionne sur CPU", "36× temps réel sur T4 GPU", "Apache 2.0 — souveraineté totale", "$0,70/1M chars en mode géré"],
    weaknesses: ["No voice cloning", "English only (American/British)", "Limited emotion control", "No lip-sync data"],
    weaknessesFr: ["Pas de clonage vocal", "Anglais uniquement (américain/britannique)", "Contrôle émotion limité", "Pas de données lip-sync"],
    digiDoubleRelevance: "Strong candidate for sovereign Phase 1 MVP. Runs on Swiss Exoscale GPU infrastructure. No voice cloning is a significant limitation for personalized GamiWays use cases. Pair with XTTS-v2 or Chatterbox for voice cloning needs.",
    digiDoubleRelevanceFr: "Candidat fort pour le MVP Phase 1 souverain. Fonctionne sur l'infrastructure GPU Exoscale suisse. L'absence de clonage vocal est une limitation significative pour les cas d'usage GamiWays personnalisés. Coupler avec XTTS-v2 ou Chatterbox pour les besoins de clonage vocal.",
    digiDoubleAxis: "Phase 1 MVP — Souveraineté maximale",
    benchmarkRef: "Artificial Analysis Speech Leaderboard, Jan 2026",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Kokoro 82M v1.0 ELO 1055 (rank #14, Apr 2026). Apache 2.0. Replicate hosted: $0.65/1M chars. Self-hosted: free. 8 languages confirmed.",
    sources: [
      { label: "Kokoro GitHub", url: "https://github.com/hexgrad/kokoro", type: "docs" },
      { label: "Kokoro on Replicate", url: "https://replicate.com/hexgrad/kokoro-82m", type: "pricing" },
      { label: "Artificial Analysis TTS", url: "https://artificialanalysis.ai/text-to-speech", type: "benchmark" },
      { label: "HuggingFace Kokoro", url: "https://huggingface.co/hexgrad/Kokoro-82M", type: "docs" },
    ],
  },
  {
    id: "chatterbox",
    name: "Chatterbox (Resemble AI)",
    category: "open-source",
    tagline: "MIT license — beats ElevenLabs in blind tests (63.75% preference)",
    homepageUrl: "https://www.resemble.ai/chatterbox/",
    docsUrl: "https://github.com/resemble-ai/chatterbox",
    ttfaMs: 150,
    ttfaMsTypical: 300,
    architecture: "Flow matching + 1-step decoder (350M params)",
    params: "350M",
    license: "MIT",
    selfHostable: true,
    selfHostNote: "Full self-hosting. MIT license. GPU recommended (RTX 3090 or better for real-time).",
    pricePerMChar: 40,
    pricePerMin: 0.04,
    priceNote: "$40/1M chars (Chatterbox HD managed). Self-hosted: near-zero cost.",
    freeTier: "Free (open weights, MIT)",
    eloScore: 1006,
    eloRank: 18,
    voiceCloning: true,
    voiceCloningDetail: "Zero-shot voice cloning. Emotional exaggeration control parameter. 63.75% preference vs ElevenLabs in blind tests.",
    streaming: true,
    streamingDetail: "Streaming capable. ~150ms TTFA on GPU. 1-step decoder reduces latency vs multi-step models.",
    multilingual: false,
    languages: 1,
    emotionControl: true,
    emotionDetail: "Emotional exaggeration control parameter (0–1 scale). Unique feature for expressive synthesis.",
    lipsyncData: false,
    lipsyncDetail: "No native lip-sync data. Can be paired with external aligner.",
    onPremise: true,
    onPremiseDetail: "Full self-hosting under MIT license. No usage restrictions.",
    gdprCompliant: true,
    dataResidency: "Fully local — no data leaves the server.",
    score: { quality: 7, latency: 7, voiceCloning: 8, expressiveness: 8, sovereignty: 10, pricing: 9, multilingual: 1 },
    description: "Chatterbox by Resemble AI achieved 63.75% user preference vs ElevenLabs in blind tests. MIT license enables unrestricted commercial use and self-hosting. Emotional exaggeration control parameter is unique. 350M params with 1-step decoder. #1 trending TTS on HuggingFace in December 2025.",
    descriptionFr: "Chatterbox de Resemble AI a obtenu 63,75% de préférence utilisateur vs ElevenLabs en tests aveugles. Licence MIT pour usage commercial et auto-hébergement sans restriction. Paramètre de contrôle d'exagération émotionnelle unique. 350M params avec décodeur 1 étape. #1 TTS trending sur HuggingFace en décembre 2025.",
    strengths: ["63.75% preference vs ElevenLabs (blind test)", "MIT license — unrestricted use", "Emotional exaggeration control", "Zero-shot voice cloning", "#1 HuggingFace trending Dec 2025"],
    strengthsFr: ["63,75% préférence vs ElevenLabs (test aveugle)", "Licence MIT — usage sans restriction", "Contrôle exagération émotionnelle", "Clonage vocal zero-shot", "#1 HuggingFace trending déc 2025"],
    weaknesses: ["English only", "GPU required for real-time", "No lip-sync data", "$40/1M chars managed (4× Inworld)"],
    weaknessesFr: ["Anglais uniquement", "GPU requis pour temps réel", "Pas de données lip-sync", "$40/1M chars géré (4× Inworld)"],
    digiDoubleRelevance: "Excellent for sovereign Phase 1 MVP with voice cloning. MIT license enables unrestricted deployment on Swiss infrastructure. English-only is a limitation for multilingual GamiWays use cases. Emotional exaggeration control aligns with Axis 2 (expressive avatar).",
    digiDoubleRelevanceFr: "Excellent pour le MVP Phase 1 souverain avec clonage vocal. Licence MIT pour déploiement sans restriction sur infrastructure suisse. Anglais uniquement est une limitation pour les cas d'usage multilingues GamiWays. Contrôle d'exagération émotionnelle aligné avec l'Axe 2 (avatar expressif).",
    digiDoubleAxis: "Phase 1 MVP — Clonage vocal souverain",
    benchmarkRef: "Artificial Analysis TTS mai 2026 + Resemble AI benchmark",
    dataUpdatedAt: "2026-05-03",
    dataUpdateNote: "Chatterbox v1 (avr 2025) : ELO 1006 (Artificial Analysis mai 2026, #18 classement). 63,75% préférence vs ElevenLabs (test aveugle, jan 2026). MIT license. 350M params, flow matching + décodeur 1 étape. Chatterbox v2 en développement (support multilingual annoncé). Clonage vocal : OUI (zero-shot). Managed : $40/1M chars. Self-hosted : gratuit.",
    sources: [
      { label: "Chatterbox GitHub", url: "https://github.com/resemble-ai/chatterbox", type: "docs" },
      { label: "Resemble AI Blog", url: "https://www.resemble.ai/chatterbox", type: "news" },
      { label: "HuggingFace TTS Arena", url: "https://huggingface.co/spaces/Pendrokar/TTS-Spaces-Arena", type: "benchmark" },
      { label: "Artificial Analysis TTS Benchmarks", url: "https://artificialanalysis.ai/text-to-speech", type: "benchmark" },
      { label: "Chatterbox HuggingFace", url: "https://huggingface.co/ResembleAI/chatterbox", type: "docs" },
    ],
  },
  {
    id: "orpheus",
    name: "Orpheus 3B",
    category: "open-source",
    tagline: "LLM-based TTS — ultra-natural speech with emotion tags and non-verbals",
    homepageUrl: "https://github.com/canopyai/Orpheus-TTS",
    docsUrl: "https://github.com/canopyai/Orpheus-TTS",
    ttfaMs: 200,
    ttfaMsTypical: 500,
    architecture: "LLaMA 3-based language model fine-tuned for speech",
    params: "3B",
    license: "Apache 2.0",
    selfHostable: true,
    selfHostNote: "Self-hosting on GPU (A100 recommended for real-time). fp8/fp16 inference via Baseten partnership.",
    pricePerMChar: 0,
    pricePerMin: 0,
    priceNote: "Open weights — self-hosting cost only. Managed inference via Baseten.",
    freeTier: "Free (open weights)",
    eloScore: 0,
    eloRank: 0,
    voiceCloning: true,
    voiceCloningDetail: "Robust voice cloning. Configurable size variants. Multi-lingual support.",
    streaming: true,
    streamingDetail: "Streaming capable. ~200ms TTFA on A100. Production-ready via Baseten.",
    multilingual: true,
    languages: 7,
    emotionControl: true,
    emotionDetail: "Emotion tags: <laugh>, <sigh>, <cough>, <gasp>, <chuckle>, <sob>. Non-verbal sounds natively supported.",
    lipsyncData: false,
    lipsyncDetail: "No native lip-sync data.",
    onPremise: true,
    onPremiseDetail: "Full self-hosting under Apache 2.0. Production deployment via Baseten at fp8/fp16.",
    gdprCompliant: true,
    dataResidency: "Fully local when self-hosted.",
    score: { quality: 8, latency: 6, voiceCloning: 7, expressiveness: 9, sovereignty: 10, pricing: 10, multilingual: 5 },
    description: "Orpheus 3B is an LLaMA 3-based TTS model fine-tuned for ultra-natural speech. Unique emotion tags (<laugh>, <sigh>, <cough>, <gasp>) enable non-verbal sounds natively. Apache 2.0 license. Production-ready via Baseten (fp8/fp16 inference). Excellent for expressive, human-like voice synthesis.",
    descriptionFr: "Orpheus 3B est un modèle TTS basé sur LLaMA 3, fine-tuné pour une synthèse vocale ultra-naturelle. Les tags émotion uniques (<laugh>, <sigh>, <cough>, <gasp>) permettent des sons non-verbaux nativement. Licence Apache 2.0. Prêt pour la production via Baseten (inférence fp8/fp16). Excellent pour la synthèse vocale expressive et humaine.",
    strengths: ["LLaMA 3-based — natural speech quality", "Non-verbal sounds: <laugh>, <cough>, <gasp>", "Apache 2.0 — full sovereignty", "Production-ready via Baseten", "7 languages"],
    strengthsFr: ["Basé LLaMA 3 — qualité vocale naturelle", "Sons non-verbaux : <laugh>, <cough>, <gasp>", "Apache 2.0 — souveraineté totale", "Prêt production via Baseten", "7 langues"],
    weaknesses: ["3B params — requires A100 for real-time", "~200ms TTFA (slower than Kokoro)", "No lip-sync data"],
    weaknessesFr: ["3B params — nécessite A100 pour temps réel", "~200ms TTFA (plus lent que Kokoro)", "Pas de données lip-sync"],
    digiDoubleRelevance: "Highly relevant for Phase 1 MVP. Non-verbal sounds (<laugh>, <sigh>) create more natural conversation. Apache 2.0 enables sovereign deployment on Exoscale. Requires A100 GPU — compatible with existing GamiWays infrastructure.",
    digiDoubleRelevanceFr: "Très pertinent pour le MVP Phase 1. Les sons non-verbaux (<laugh>, <sigh>) créent une conversation plus naturelle. Apache 2.0 pour déploiement souverain sur Exoscale. Nécessite GPU A100 — compatible avec l'infrastructure GamiWays existante.",
    digiDoubleAxis: "Phase 1 MVP — Expressivité naturelle",
    benchmarkRef: "Canopy AI GitHub + Modal.com TTS comparison, 2025",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Orpheus 3B released Jan 2025. Apache 2.0. 3B params. Emotion tags (laugh, sigh, etc.). Self-hosted on GPU. 7 languages.",
    sources: [
      { label: "Orpheus GitHub", url: "https://github.com/canopyai/Orpheus-TTS", type: "docs" },
      { label: "Canopy AI Blog", url: "https://canopylabs.ai/model-releases", type: "news" },
      { label: "Artificial Analysis TTS", url: "https://artificialanalysis.ai/text-to-speech", type: "benchmark" },
    ],
  },
  {
    id: "dia",
    name: "Dia (Nari Labs)",
    category: "open-source",
    tagline: "Ultra-realistic dialogue generation — multi-speaker, emotion, non-verbals",
    homepageUrl: "https://github.com/nari-labs/dia",
    docsUrl: "https://github.com/nari-labs/dia",
    ttfaMs: 300,
    ttfaMsTypical: 800,
    architecture: "Transformer (1.6B params) — dialogue-specialized",
    params: "1.6B",
    license: "Apache 2.0",
    selfHostable: true,
    selfHostNote: "Self-hosting on GPU (RTX 3090 or better). Not optimized for real-time streaming.",
    pricePerMChar: 0,
    pricePerMin: 0,
    priceNote: "Open weights — self-hosting cost only.",
    freeTier: "Free (open weights)",
    eloScore: 0,
    eloRank: 0,
    voiceCloning: true,
    voiceCloningDetail: "Condition on audio for emotion and tone control. Multi-speaker dialogue generation.",
    streaming: false,
    streamingDetail: "Not optimized for streaming. Batch generation. ~300ms+ TTFA.",
    multilingual: false,
    languages: 1,
    emotionControl: true,
    emotionDetail: "Audio conditioning for emotion and tone. Non-verbal sounds. Multi-speaker with distinct voices.",
    lipsyncData: false,
    lipsyncDetail: "No native lip-sync data.",
    onPremise: true,
    onPremiseDetail: "Full self-hosting under Apache 2.0.",
    gdprCompliant: true,
    dataResidency: "Fully local when self-hosted.",
    score: { quality: 8, latency: 4, voiceCloning: 7, expressiveness: 9, sovereignty: 10, pricing: 10, multilingual: 1 },
    description: "Dia by Nari Labs generates ultra-realistic dialogue directly from transcripts. Unique multi-speaker capability with distinct voices, emotion conditioning, and non-verbal sounds. Apache 2.0. Not optimized for real-time streaming — best for pre-rendered dialogue or batch generation. Challenged ElevenLabs at launch (April 2025).",
    descriptionFr: "Dia de Nari Labs génère des dialogues ultra-réalistes directement depuis des transcriptions. Capacité multi-locuteurs unique avec des voix distinctes, conditionnement émotionnel et sons non-verbaux. Apache 2.0. Non optimisé pour le streaming temps réel — idéal pour la génération de dialogues pré-rendus ou par lots. A challengé ElevenLabs à son lancement (avril 2025).",
    strengths: ["Ultra-realistic multi-speaker dialogue", "Audio conditioning for emotion", "Non-verbal sounds", "Apache 2.0 — full sovereignty", "Unique dialogue-first design"],
    strengthsFr: ["Dialogue multi-locuteurs ultra-réaliste", "Conditionnement audio pour l'émotion", "Sons non-verbaux", "Apache 2.0 — souveraineté totale", "Design dialogue-first unique"],
    weaknesses: ["Not optimized for real-time streaming", "English only", "~300ms+ TTFA", "No lip-sync data"],
    weaknessesFr: ["Non optimisé pour le streaming temps réel", "Anglais uniquement", "~300ms+ TTFA", "Pas de données lip-sync"],
    digiDoubleRelevance: "Relevant for pre-rendered dialogue sequences (narrative mode). Multi-speaker capability useful for generating training data. Not suitable for real-time Phase 1 MVP due to lack of streaming optimization.",
    digiDoubleRelevanceFr: "Pertinent pour les séquences de dialogue pré-rendues (mode narratif). Capacité multi-locuteurs utile pour générer des données d'entraînement. Non adapté au MVP Phase 1 temps réel en raison du manque d'optimisation streaming.",
    digiDoubleAxis: "Mode narratif — Génération dialogue pré-rendu",
    benchmarkRef: "Nari Labs GitHub + VentureBeat, Apr 2025",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Dia 1.6B released Apr 2025 by Nari Labs. Apache 2.0. Dialogue-native TTS with [S1]/[S2] speaker tags. Self-hosted on GPU.",
    sources: [
      { label: "Dia GitHub", url: "https://github.com/nari-labs/dia", type: "docs" },
      { label: "Nari Labs Blog", url: "https://nari-labs.github.io/Dia/", type: "news" },
      { label: "HuggingFace Dia", url: "https://huggingface.co/nari-labs/Dia-1.6B", type: "docs" },
    ],
  },
  {
    id: "kyutai_tts",
    name: "Kyutai TTS 1.6B",
    category: "open-source",
    tagline: "Delayed streams modeling — streaming-native, timestamps, batching",
    homepageUrl: "https://kyutai.org/tts",
    docsUrl: "https://github.com/kyutai-labs/moshi",
    ttfaMs: 100,
    ttfaMsTypical: 200,
    architecture: "Delayed streams modeling (novel technique)",
    params: "1.6B",
    license: "CC-BY 4.0",
    selfHostable: true,
    selfHostNote: "Self-hosting on GPU. Streaming-native architecture enables low-latency deployment.",
    pricePerMChar: 0,
    pricePerMin: 0,
    priceNote: "Open weights — self-hosting cost only.",
    freeTier: "Free (open weights)",
    eloScore: 0,
    eloRank: 0,
    voiceCloning: true,
    voiceCloningDetail: "Voice conditioning from audio samples. Related to Moshi speech-to-speech model.",
    streaming: true,
    streamingDetail: "Streaming-native via delayed streams modeling. Timestamps enabled. Batching supported.",
    multilingual: false,
    languages: 2,
    emotionControl: false,
    emotionDetail: "Natural prosody. Limited explicit emotion control.",
    lipsyncData: true,
    lipsyncDetail: "Timestamps natively supported via delayed streams modeling.",
    onPremise: true,
    onPremiseDetail: "Full self-hosting under CC-BY 4.0.",
    gdprCompliant: true,
    dataResidency: "Fully local when self-hosted.",
    score: { quality: 7, latency: 8, voiceCloning: 6, expressiveness: 6, sovereignty: 10, pricing: 10, multilingual: 2 },
    description: "Kyutai TTS 1.6B uses a novel 'delayed streams modeling' technique enabling streaming-native generation with timestamps and batching. Released July 2025 by Kyutai (French AI lab, creators of Moshi). CC-BY 4.0 license. Related to Moshi full-duplex speech model. Unique architecture worth studying for Axis 1 R&D.",
    descriptionFr: "Kyutai TTS 1.6B utilise une technique novatrice de 'modélisation par flux décalés' permettant une génération streaming-native avec timestamps et batching. Publié en juillet 2025 par Kyutai (labo IA français, créateurs de Moshi). Licence CC-BY 4.0. Lié au modèle speech full-duplex Moshi. Architecture unique à étudier pour l'Axe 1 R&D.",
    strengths: ["Streaming-native via delayed streams", "Native timestamps for lip-sync", "Batching support", "CC-BY 4.0 — sovereign deployment", "From Kyutai (Moshi creators)"],
    strengthsFr: ["Streaming-native via flux décalés", "Timestamps natifs pour lip-sync", "Support batching", "CC-BY 4.0 — déploiement souverain", "De Kyutai (créateurs de Moshi)"],
    weaknesses: ["Limited language support", "Limited emotion control", "Less community adoption than Kokoro/Chatterbox"],
    weaknessesFr: ["Support linguistique limité", "Contrôle émotion limité", "Moins d'adoption communautaire que Kokoro/Chatterbox"],
    digiDoubleRelevance: "Interesting for Axis 1 R&D (latency). Delayed streams modeling is a novel architecture worth studying. Native timestamps directly usable for avatar lip-sync. CC-BY 4.0 enables sovereign deployment.",
    digiDoubleRelevanceFr: "Intéressant pour l'Axe 1 R&D (latence). La modélisation par flux décalés est une architecture novatrice à étudier. Timestamps natifs directement utilisables pour le lip-sync avatar. CC-BY 4.0 pour déploiement souverain.",
    digiDoubleAxis: "Axe 1 R&D — Architecture streaming",
    benchmarkRef: "Kyutai blog Jul 2025 + Artificial Analysis TTS mai 2026",
    dataUpdatedAt: "2026-05-03",
    dataUpdateNote: "Kyutai TTS 1.6B (juil 2025) : architecture 'delayed streams modeling' unique. CC-BY 4.0. Labo français Kyutai (créateurs de Moshi full-duplex). Moshi 2 en développement (annoncé 2026). Langues : EN + FR. Timestamps natifs pour lip-sync. Batching support. ELO non encore classé sur Artificial Analysis. Clonage vocal : voice conditioning audio (partiel). Self-hosted sur GPU.",
    sources: [
      { label: "Kyutai GitHub (Moshi)", url: "https://github.com/kyutai-labs/moshi", type: "docs" },
      { label: "Kyutai Blog", url: "https://kyutai.org/moshi", type: "news" },
      { label: "Kyutai TTS HuggingFace", url: "https://huggingface.co/kyutai/tts-1.6b-en_fr", type: "docs" },
      { label: "Artificial Analysis TTS", url: "https://artificialanalysis.ai/text-to-speech", type: "benchmark" },
    ],
  },
  {
    id: "sesame_csm",
    name: "Sesame CSM",
    category: "open-source",
    tagline: "Conversational Speech Model — crosses the uncanny valley of voice",
    homepageUrl: "https://www.sesame.com",
    docsUrl: "https://github.com/SesameAILabs/csm",
    ttfaMs: 400,
    ttfaMsTypical: 1000,
    architecture: "Multimodal backbone + audio decoder (RVQ tokens)",
    params: "1B+",
    license: "Apache 2.0 (research)",
    selfHostable: true,
    selfHostNote: "Self-hosting on GPU (A100 recommended). Research-grade, not production-optimized.",
    pricePerMChar: 0,
    pricePerMin: 0,
    priceNote: "Open weights — self-hosting cost only. Research use.",
    freeTier: "Free (open weights)",
    eloScore: 0,
    eloRank: 0,
    voiceCloning: true,
    voiceCloningDetail: "Context-aware voice generation. Generates RVQ audio codes from text + audio inputs. Conversational context maintained.",
    streaming: false,
    streamingDetail: "Not optimized for real-time streaming. Research model.",
    multilingual: false,
    languages: 1,
    emotionControl: true,
    emotionDetail: "Context-aware prosody. Conversational backchannels. Natural turn-taking behavior.",
    lipsyncData: false,
    lipsyncDetail: "No native lip-sync data.",
    onPremise: true,
    onPremiseDetail: "Full self-hosting under Apache 2.0.",
    gdprCompliant: true,
    dataResidency: "Fully local when self-hosted.",
    score: { quality: 9, latency: 3, voiceCloning: 7, expressiveness: 10, sovereignty: 10, pricing: 10, multilingual: 1 },
    description: "Sesame CSM (Conversational Speech Model) is a multimodal model that generates RVQ audio codes from text and audio inputs. Designed to 'cross the uncanny valley of conversational voice' — context-aware prosody, natural backchannels, turn-taking behavior. Research-grade, not production-optimized for streaming. Released March 2025.",
    descriptionFr: "Sesame CSM (Conversational Speech Model) est un modèle multimodal qui génère des codes audio RVQ à partir de texte et d'entrées audio. Conçu pour 'franchir la vallée de l'étrange de la voix conversationnelle' — prosodie contextuelle, backchannels naturels, comportement de prise de tour. Niveau recherche, non optimisé pour le streaming en production. Publié en mars 2025.",
    strengths: ["Context-aware conversational prosody", "Natural backchannels and turn-taking", "Crosses uncanny valley of voice", "Apache 2.0 — full sovereignty", "Unique multimodal architecture"],
    strengthsFr: ["Prosodie conversationnelle contextuelle", "Backchannels naturels et prise de tour", "Franchit la vallée de l'étrange vocale", "Apache 2.0 — souveraineté totale", "Architecture multimodale unique"],
    weaknesses: ["Not production-optimized for streaming", "~400ms+ TTFA", "English only", "Research-grade stability"],
    weaknessesFr: ["Non optimisé pour le streaming en production", "~400ms+ TTFA", "Anglais uniquement", "Stabilité niveau recherche"],
    digiDoubleRelevance: "Highly relevant for Axis 2 R&D (conversational behavior). Context-aware prosody and natural backchannels are exactly what GamiWays needs for authentic conversation. Not suitable for Phase 1 MVP real-time — evaluate for Axis 2 research.",
    digiDoubleRelevanceFr: "Très pertinent pour l'Axe 2 R&D (comportement conversationnel). La prosodie contextuelle et les backchannels naturels sont exactement ce dont GamiWays a besoin pour une conversation authentique. Non adapté au MVP Phase 1 temps réel — évaluer pour la recherche Axe 2.",
    digiDoubleAxis: "Axe 2 R&D — Comportement conversationnel",
    benchmarkRef: "Sesame AI research blog, Mar 2025",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Sesame CSM released Mar 2025. Apache 2.0. 1B params. Conversational speech model with natural prosody. Self-hosted.",
    sources: [
      { label: "Sesame AI Blog", url: "https://www.sesame.com/research/crossing_the_uncanny_valley_of_voice", type: "news" },
      { label: "Sesame CSM GitHub", url: "https://github.com/SesameAILabs/csm", type: "docs" },
      { label: "HuggingFace CSM", url: "https://huggingface.co/sesame/csm-1b", type: "docs" },
    ],
  },

  // ─── VOICE-TO-VOICE (END-TO-END) ────────────────────────────────────────────────
  {
    id: "ultravox",
    name: "Ultravox v0.5",
    category: "open-source",
    tagline: "Speech-to-speech model — ~100ms latency, no ASR/TTS pipeline needed",
    homepageUrl: "https://ultravox.ai",
    docsUrl: "https://docs.ultravox.ai",
    ttfaMs: 100,
    ttfaMsTypical: 300,
    architecture: "End-to-end speech-to-speech (no cascading ASR+LLM+TTS)",
    params: "8B (Llama-based)",
    license: "Commercial API (CC-BY-NC-4.0 weights)",
    selfHostable: true,
    selfHostNote: "Weights available under CC-BY-NC-4.0. Production deployment via Cerebrium/Pipecat.",
    pricePerMChar: 0,
    pricePerMin: 0.05,
    priceNote: "~$0.05/min API. Self-hosted: GPU cost only.",
    freeTier: "Limited free tier",
    eloScore: 0,
    eloRank: 0,
    voiceCloning: false,
    voiceCloningDetail: "No voice cloning. Fixed voice output.",
    streaming: true,
    streamingDetail: "~100ms response latency. Full-duplex capable. Eliminates ASR+LLM+TTS pipeline latency accumulation.",
    multilingual: true,
    languages: 10,
    emotionControl: false,
    emotionDetail: "Natural prosody from end-to-end training. Limited explicit emotion control.",
    lipsyncData: false,
    lipsyncDetail: "No native lip-sync data.",
    onPremise: true,
    onPremiseDetail: "Weights available under CC-BY-NC-4.0. Non-commercial self-hosting.",
    gdprCompliant: true,
    dataResidency: "Self-hosted: fully local.",
    score: { quality: 7, latency: 10, voiceCloning: 1, expressiveness: 6, sovereignty: 7, pricing: 7, multilingual: 5 },
    description: "Ultravox v0.5 is an end-to-end speech-to-speech model that eliminates the cascading ASR+LLM+TTS pipeline. ~100ms response latency vs 800ms–2s for cascading systems. Turn reliability: 300/300 vs 296/300 for GPT-4o Realtime. Median response latency: 0.864s vs 1.536s for GPT-4o. Best for latency-critical voice agents.",
    descriptionFr: "Ultravox v0.5 est un modèle speech-to-speech end-to-end qui élimine le pipeline en cascade ASR+LLM+TTS. ~100ms de latence de réponse vs 800ms–2s pour les systèmes en cascade. Fiabilité de tour : 300/300 vs 296/300 pour GPT-4o Realtime. Latence médiane : 0,864s vs 1,536s pour GPT-4o. Idéal pour les agents vocaux à latence critique.",
    strengths: ["~100ms response latency", "Eliminates cascading pipeline overhead", "300/300 turn reliability", "0.864s median latency vs 1.536s GPT-4o", "End-to-end speech understanding"],
    strengthsFr: ["~100ms latence de réponse", "Élimine la surcharge du pipeline en cascade", "300/300 fiabilité de tour", "0,864s latence médiane vs 1,536s GPT-4o", "Compréhension vocale end-to-end"],
    weaknesses: ["No voice cloning", "CC-BY-NC-4.0 — non-commercial self-hosting only", "Less controllable than cascading systems", "No lip-sync data"],
    weaknessesFr: ["Pas de clonage vocal", "CC-BY-NC-4.0 — auto-hébergement non-commercial uniquement", "Moins contrôlable que les systèmes en cascade", "Pas de données lip-sync"],
    digiDoubleRelevance: "Critical reference for Phase 1 MVP architecture decision: cascading (ASR+LLM+TTS) vs end-to-end (Ultravox). End-to-end eliminates latency accumulation but loses controllability. GamiWays Phase 1 should benchmark both approaches. CC-BY-NC-4.0 limits commercial self-hosting.",
    digiDoubleRelevanceFr: "Référence critique pour la décision d'architecture du MVP Phase 1 : en cascade (ASR+LLM+TTS) vs end-to-end (Ultravox). L'end-to-end élimine l'accumulation de latence mais perd en contrôlabilité. GamiWays Phase 1 devrait benchmarker les deux approches. CC-BY-NC-4.0 limite l'auto-hébergement commercial.",
    digiDoubleAxis: "Phase 1 MVP — Architecture V2V end-to-end",
    benchmarkRef: "Ultravox AIEWF eval, Feb 2026",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Ultravox v0.5 released Feb 2026. MIT license. End-to-end S2S, no separate TTS. Llama 3.1 backbone. Self-hosted or Fixie.ai API. AIEWF eval: 0.864s median latency.",
    sources: [
      { label: "Ultravox GitHub", url: "https://github.com/fixie-ai/ultravox", type: "docs" },
      { label: "Ultravox Website", url: "https://www.ultravox.ai", type: "docs" },
      { label: "AIEWF Evaluation Feb 2026", url: "https://artificialanalysis.ai/speech-to-text", type: "benchmark" },
    ],
  },
  {
    id: "moshi",
    name: "Moshi (Kyutai)",
    category: "open-source",
    tagline: "Full-duplex spoken dialogue — simultaneous listening and speaking",
    homepageUrl: "https://kyutai.org",
    docsUrl: "https://github.com/kyutai-labs/moshi",
    ttfaMs: 200,
    ttfaMsTypical: 500,
    architecture: "Speech-text foundation model + Mimi codec (full-duplex)",
    params: "7B",
    license: "CC-BY 4.0",
    selfHostable: true,
    selfHostNote: "Full self-hosting under CC-BY 4.0. Requires A100 GPU for real-time.",
    pricePerMChar: 0,
    pricePerMin: 0,
    priceNote: "Open weights — self-hosting cost only.",
    freeTier: "Free (open weights)",
    eloScore: 0,
    eloRank: 0,
    voiceCloning: false,
    voiceCloningDetail: "No voice cloning. Fixed voice output.",
    streaming: true,
    streamingDetail: "Full-duplex: simultaneous listening and speaking. Streaming neural audio codec (Mimi). Real-time capable on A100.",
    multilingual: false,
    languages: 1,
    emotionControl: false,
    emotionDetail: "Natural prosody from end-to-end training. No explicit emotion control.",
    lipsyncData: false,
    lipsyncDetail: "No native lip-sync data.",
    onPremise: true,
    onPremiseDetail: "Full self-hosting under CC-BY 4.0. Commercial use allowed.",
    gdprCompliant: true,
    dataResidency: "Fully local when self-hosted.",
    score: { quality: 7, latency: 8, voiceCloning: 1, expressiveness: 6, sovereignty: 10, pricing: 10, multilingual: 1 },
    description: "Moshi is a full-duplex speech-text foundation model from Kyutai (French AI lab). Enables simultaneous listening and speaking — unlike turn-based systems. Uses Mimi streaming neural audio codec. CC-BY 4.0 license enables sovereign deployment. Reference for full-duplex conversation research.",
    descriptionFr: "Moshi est un modèle fondation speech-text full-duplex de Kyutai (labo IA français). Permet l'écoute et la parole simultanées — contrairement aux systèmes à tours. Utilise le codec audio neuronal streaming Mimi. Licence CC-BY 4.0 pour déploiement souverain. Référence pour la recherche sur la conversation full-duplex.",
    strengths: ["Full-duplex: simultaneous listen + speak", "CC-BY 4.0 — commercial sovereign deployment", "Mimi streaming codec", "From Kyutai (European AI lab)", "Research reference for full-duplex"],
    strengthsFr: ["Full-duplex : écoute + parole simultanées", "CC-BY 4.0 — déploiement souverain commercial", "Codec streaming Mimi", "De Kyutai (labo IA européen)", "Référence recherche full-duplex"],
    weaknesses: ["English only", "Requires A100 for real-time", "No voice cloning", "Research-grade stability"],
    weaknessesFr: ["Anglais uniquement", "Nécessite A100 pour temps réel", "Pas de clonage vocal", "Stabilité niveau recherche"],
    digiDoubleRelevance: "Key reference for Axis 1 R&D (full-duplex conversation). Full-duplex capability is the long-term goal for GamiWays — enables natural interruption handling. CC-BY 4.0 enables sovereign deployment. Not suitable for Phase 1 MVP — evaluate for Axis 1 advanced research.",
    digiDoubleRelevanceFr: "Référence clé pour l'Axe 1 R&D (conversation full-duplex). La capacité full-duplex est l'objectif à long terme pour GamiWays — permet la gestion naturelle des interruptions. CC-BY 4.0 pour déploiement souverain. Non adapté au MVP Phase 1 — évaluer pour la recherche avancée Axe 1.",
    digiDoubleAxis: "Axe 1 R&D — Full-duplex conversation",
    benchmarkRef: "Kyutai GitHub + research blog, 2024–2025",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Moshi released Sep 2024 by Kyutai. CC-BY 4.0. Full-duplex S2S with inner monologue. 7B params. Self-hosted on GPU.",
    sources: [
      { label: "Moshi GitHub", url: "https://github.com/kyutai-labs/moshi", type: "docs" },
      { label: "Kyutai Research Blog", url: "https://kyutai.org/moshi", type: "news" },
      { label: "HuggingFace Moshi", url: "https://huggingface.co/kyutai/moshi", type: "docs" },
    ],
  },
  {
    id: "voxtral_tts",
    name: "Voxtral TTS (Mistral)",
    category: "open-source",
    tagline: "Open-weights TTS from Mistral — fast, adaptable, 9 languages (Mar 2026)",
    homepageUrl: "https://mistral.ai",
    docsUrl: "https://docs.mistral.ai",
    ttfaMs: 150,
    ttfaMsTypical: 300,
    architecture: "Transformer (Mistral architecture, open-weights)",
    params: "N/A (not disclosed)",
    license: "Open weights (Mistral license)",
    selfHostable: true,
    selfHostNote: "Open weights released March 26, 2026. Self-hosting on GPU.",
    pricePerMChar: 0,
    pricePerMin: 0.02,
    priceNote: "API pricing TBD. Open weights for self-hosting.",
    freeTier: "Open weights — free for self-hosting",
    eloScore: 0,
    eloRank: 0,
    voiceCloning: true,
    voiceCloningDetail: "Instant voice adaptation. 'Instantly adaptable' per Mistral announcement.",
    streaming: true,
    streamingDetail: "Fast streaming. Designed for voice agents.",
    multilingual: true,
    languages: 9,
    emotionControl: false,
    emotionDetail: "Natural prosody. Limited explicit emotion control at launch.",
    lipsyncData: false,
    lipsyncDetail: "No native lip-sync data at launch.",
    onPremise: true,
    onPremiseDetail: "Open weights — full self-hosting possible.",
    gdprCompliant: true,
    dataResidency: "EU (Mistral is French company). Self-hosted: fully local.",
    score: { quality: 8, latency: 8, voiceCloning: 7, expressiveness: 6, sovereignty: 9, pricing: 9, multilingual: 6 },
    description: "Voxtral TTS was released by Mistral AI on March 26, 2026 — just 3 days before this research was compiled. Open-weights frontier TTS model supporting 9 languages (EN, FR, DE, ES, NL, PT, IT, HI, AR). Designed for voice agents: fast, instantly adaptable, lifelike speech. European AI lab — strong alignment with Swiss sovereignty requirements.",
    descriptionFr: "Voxtral TTS a été publié par Mistral AI le 26 mars 2026 — 3 jours avant la compilation de cette recherche. Modèle TTS frontier open-weights supportant 9 langues (EN, FR, DE, ES, NL, PT, IT, HI, AR). Conçu pour les agents vocaux : rapide, instantanément adaptable, parole réaliste. Labo IA européen — fort alignement avec les exigences de souveraineté suisse.",
    strengths: ["Open-weights — sovereign deployment", "9 languages including FR, DE", "European AI lab (Mistral)", "Fast + instantly adaptable", "Released March 2026 — cutting edge"],
    strengthsFr: ["Open-weights — déploiement souverain", "9 langues dont FR, DE", "Labo IA européen (Mistral)", "Rapide + instantanément adaptable", "Publié mars 2026 — état de l'art"],
    weaknesses: ["Very new — no production track record", "Limited documentation at launch", "No lip-sync data", "Emotion control not detailed"],
    weaknessesFr: ["Très récent — pas de track record production", "Documentation limitée au lancement", "Pas de données lip-sync", "Contrôle émotion non détaillé"],
    digiDoubleRelevance: "High priority evaluation for Phase 1 MVP. European open-weights model with French/German support aligns perfectly with GamiWays's Swiss sovereign deployment requirements. Very new — needs production testing. Mistral ecosystem integration with Voxtral ASR creates a potential full-stack sovereign solution.",
    digiDoubleRelevanceFr: "Évaluation haute priorité pour le MVP Phase 1. Modèle open-weights européen avec support français/allemand parfaitement aligné avec les exigences de déploiement souverain suisse de GamiWays. Très récent — nécessite des tests en production. L'intégration avec l'écosystème Mistral/Voxtral ASR crée une solution souveraine full-stack potentielle.",
    digiDoubleAxis: "Phase 1 MVP — Souveraineté européenne",
    benchmarkRef: "Mistral AI announcement, Mar 26, 2026",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "Voxtral TTS announced Mar 26, 2026 by Mistral AI. Open-weights. 9 languages (EN, FR, DE, ES, NL, PT, IT, HI, AR). ELO not yet in Artificial Analysis leaderboard. Production benchmarks pending.",
    sources: [
      { label: "Mistral Voxtral Announcement", url: "https://mistral.ai/news/voxtral", type: "news" },
      { label: "Mistral API Pricing", url: "https://mistral.ai/technology/#pricing", type: "pricing" },
      { label: "Mistral Docs", url: "https://docs.mistral.ai", type: "docs" },
    ],
  },
  {
    id: "openai_realtime",
    name: "OpenAI Realtime API",
    category: "cloud-api",
    tagline: "GPT-4o speech-to-speech — integrated LLM + voice, WebSocket",
    homepageUrl: "https://platform.openai.com/docs/guides/realtime",
    docsUrl: "https://platform.openai.com/docs/guides/realtime",
    ttfaMs: 300,
    ttfaMsTypical: 700,
    architecture: "GPT-4o multimodal (speech-to-speech, integrated LLM)",
    params: "N/A (cloud, GPT-4o scale)",
    license: "Commercial",
    selfHostable: false,
    selfHostNote: "Cloud only. No on-premise option.",
    pricePerMChar: 0,
    pricePerMin: 0.10,
    priceNote: "$0.06/min audio input + $0.24/min audio output (GPT-4o Realtime). ~$0.10/min average.",
    freeTier: "API credits on signup",
    eloScore: 1208,
    eloRank: 1,
    voiceCloning: false,
    voiceCloningDetail: "No voice cloning. 6 pre-built voices (Alloy, Echo, Fable, Onyx, Nova, Shimmer).",
    streaming: true,
    streamingDetail: "WebSocket streaming. Full-duplex capable. Integrated with GPT-4o reasoning. 1.536s median latency (vs 0.864s for Ultravox).",
    multilingual: true,
    languages: 50,
    emotionControl: true,
    emotionDetail: "Natural emotional range from GPT-4o. Limited explicit emotion control.",
    lipsyncData: false,
    lipsyncDetail: "No native lip-sync data.",
    onPremise: false,
    onPremiseDetail: "Cloud only. No on-premise option.",
    gdprCompliant: true,
    dataResidency: "US (default). EU data residency on enterprise.",
    score: { quality: 8, latency: 6, voiceCloning: 1, expressiveness: 7, sovereignty: 1, pricing: 4, multilingual: 9 },
    description: "OpenAI Realtime API provides GPT-4o speech-to-speech with integrated reasoning. WebSocket streaming, full-duplex capable. ELO 1208 (TTS rank #1, May 2026). 1.536s median latency vs 0.864s for Ultravox. No voice cloning, no sovereignty. Best for teams already in OpenAI ecosystem needing integrated LLM+voice.",
    descriptionFr: "L'API Realtime d'OpenAI fournit GPT-4o speech-to-speech avec raisonnement intégré. Streaming WebSocket, capable full-duplex. ELO 1208 (rang TTS #1, mai 2026). Latence médiane 1,536s vs 0,864s pour Ultravox. Pas de clonage vocal, pas de souveraineté. Idéal pour les équipes déjà dans l'écosystème OpenAI nécessitant LLM+voix intégré.",
    strengths: ["GPT-4o reasoning integrated", "ELO 1208 — rank #1", "50+ languages", "WebSocket full-duplex", "Well-documented API"],
    strengthsFr: ["Raisonnement GPT-4o intégré", "ELO 1208 — rang #1", "50+ langues", "WebSocket full-duplex", "API bien documentée"],
    weaknesses: ["No voice cloning", "No sovereignty (US cloud)", "$0.10/min — expensive at scale", "1.536s median latency (vs 0.864s Ultravox)"],
    weaknessesFr: ["Pas de clonage vocal", "Pas de souveraineté (cloud US)", "$0,10/min — coûteux à l'échelle", "1,536s latence médiane (vs 0,864s Ultravox)"],
    digiDoubleRelevance: "Reference for Phase 1 MVP benchmarking. Not suitable for production GamiWays due to no sovereignty and no voice cloning. Use as quality/latency benchmark. Compare against Ultravox (end-to-end) and cascading sovereign stack.",
    digiDoubleRelevanceFr: "Référence pour le benchmarking du MVP Phase 1. Non adapté à la production GamiWays en raison de l'absence de souveraineté et de clonage vocal. Utiliser comme benchmark qualité/latence. Comparer avec Ultravox (end-to-end) et le stack souverain en cascade.",
    digiDoubleAxis: "Phase 1 MVP — Référence benchmark",
    benchmarkRef: "OpenAI docs + Ultravox AIEWF eval, Feb 2026",
    dataUpdatedAt: "2026-04-30",
    dataUpdateNote: "OpenAI Realtime API (GPT-4o) pricing: $0.06/min audio input + $0.24/min audio output. ELO 1208 (rank #1, May 2026). TTFA ~300ms. WebSocket streaming. 57 languages. No on-premise.",
    sources: [
      { label: "OpenAI Realtime API Pricing", url: "https://openai.com/api/pricing/", type: "pricing" },
      { label: "OpenAI Realtime API Docs", url: "https://platform.openai.com/docs/guides/realtime", type: "docs" },
      { label: "Artificial Analysis TTS", url: "https://artificialanalysis.ai/text-to-speech", type: "benchmark" },
    ],
  },
  {
    id: "stepaudio_25",
    name: "StepAudio 2.5 TTS",
    category: "cloud-api",
    tagline: "Contextual TTS — ELO 1187, dual-level context control, zero-shot voice cloning in 3 sec",
    homepageUrl: "https://platform.stepfun.ai",
    docsUrl: "https://platform.stepfun.ai/docs/en/guides/models/stepaudio-2.5-tts",
    ttfaMs: 200,
    ttfaMsTypical: 400,
    architecture: "End-to-end contextual TTS (NTP-based, no speaker/emotion embeddings)",
    params: "Undisclosed",
    license: "Proprietary (StepFun / 阶跃星辰)",
    selfHostable: false,
    selfHostNote: "Cloud-only. No on-premise option. Enterprise plans available.",
    pricePerMChar: 85,
    pricePerMin: 0.064,
    priceNote: "$0.85/10K chars ($85/1M chars). Voice cloning: $1.50/voice. step-tts-2 (standard): $0.40/10K chars ($40/1M chars).",
    freeTier: "No public free tier. API key required.",
    eloScore: 1187,
    eloRank: 3,
    voiceCloning: true,
    voiceCloningDetail: "Zero-shot voice cloning from just 3 seconds of reference audio. Full Global/Inline context control inherited by cloned voice. $1.50/voice.",
    streaming: true,
    streamingDetail: "WebSocket streaming via /v1/realtime/audio. Non-streaming POST /v1/audio/speech also available.",
    multilingual: true,
    languages: 100,
    emotionControl: true,
    emotionDetail: "Dual-level context control: Global Context (overall tone, natural language description) + Inline Context (per-sentence via parentheses). Supports complex intents like 'restrained sadness, no sobbing, with a slight tremble'.",
    lipsyncData: false,
    lipsyncDetail: "No native lip-sync timestamps. External aligner required.",
    onPremise: false,
    onPremiseDetail: "Cloud-only. StepFun is a Shanghai-based company (Chinese jurisdiction).",
    gdprCompliant: false,
    dataResidency: "China (StepFun servers, Shanghai). No EU data residency option.",
    score: { quality: 10, latency: 6, voiceCloning: 9, expressiveness: 10, sovereignty: 1, pricing: 5, multilingual: 9 },
    description: "StepAudio 2.5 TTS (launched April 16, 2026) ranks #3 globally on Artificial Analysis Speech Arena (ELO 1187). It is the first model to integrate contextual understanding into the entire speech generation pipeline. Dual-level context control: Global Context sets the overall tone for a passage; Inline Context uses parentheses for per-sentence fine-grained control of emotion, pauses, and breathing. Zero-shot voice cloning from 3 seconds of reference audio. 100+ languages. Price: $0.85/10K chars ($0.064/min). step-tts-2 (standard): $0.40/10K chars ($0.030/min). Chinese company (StepFun, Shanghai) — no GDPR/sovereignty.",
    descriptionFr: "StepAudio 2.5 TTS (lancé le 16 avril 2026) est classé #3 mondial sur l'Artificial Analysis Speech Arena (ELO 1187). Premier modèle à intégrer la compréhension contextuelle dans toute la pipeline de génération vocale. Contrôle dual-level : Global Context définit le ton global d'un passage ; Inline Context utilise des parenthèses pour un contrôle fin par phrase (émotion, pauses, respiration). Clonage vocal zero-shot à partir de 3 secondes d'audio de référence. 100+ langues. Prix : $0,85/10K chars ($0,064/min). step-tts-2 (standard) : $0,40/10K chars ($0,030/min). Entreprise chinoise (StepFun, Shanghai) — pas de RGPD/souveraineté.",
    strengths: ["ELO 1187 — rank #3 globally (Artificial Analysis)", "Dual-level context control (Global + Inline)", "Zero-shot voice cloning from 3 sec reference", "100+ languages with crosslingual identity", "step-tts-2 at $0.030/min — competitive pricing"],
    strengthsFr: ["ELO 1187 — rang #3 mondial (Artificial Analysis)", "Contrôle dual-level (Global + Inline Context)", "Clonage vocal zero-shot à partir de 3 sec", "100+ langues avec identité crosslinguale", "step-tts-2 à $0,030/min — prix compétitif"],
    weaknesses: ["Chinese company — no GDPR, no EU data residency", "No on-premise option", "$85/1M chars (flagship) — expensive vs Inworld ($42/1M)", "No lip-sync timestamps", "Max 1000 chars per request"],
    weaknessesFr: ["Entreprise chinoise — pas de RGPD, pas de résidence EU", "Pas d'option on-premise", "$85/1M chars (flagship) — cher vs Inworld ($42/1M)", "Pas de timestamps lip-sync", "Max 1000 chars par requête"],
    digiDoubleRelevance: "Exceptional quality for storytelling and emotional content (ELO #3). The dual-level context control is a unique differentiator for GamiWays character performance. However, Chinese jurisdiction and no GDPR compliance are blocking factors for Swiss/EU clients. Recommended for quality benchmarking and non-sensitive use cases only.",
    digiDoubleRelevanceFr: "Qualité exceptionnelle pour le storytelling et le contenu émotionnel (ELO #3). Le contrôle dual-level est un différenciateur unique pour la performance de personnages GamiWays. Cependant, la juridiction chinoise et l'absence de conformité RGPD sont des facteurs bloquants pour les clients suisses/EU. Recommandé pour le benchmarking qualité et les cas d'usage non-sensibles uniquement.",
    digiDoubleAxis: "Benchmarking qualité — non recommandé pour production EU",
    benchmarkRef: "Artificial Analysis Speech Arena, May 2026",
    dataUpdatedAt: "2026-05-12",
    dataUpdateNote: "StepAudio 2.5 TTS launched April 16, 2026. ELO 1187 (rank #3, May 2026). Pricing: $0.85/10K chars (flagship), $0.40/10K chars (step-tts-2). Voice cloning: $1.50/voice. Chinese company, no GDPR.",
    sources: [
      { label: "StepAudio 2.5 TTS Docs", url: "https://platform.stepfun.ai/docs/en/guides/models/stepaudio-2.5-tts", type: "docs" },
      { label: "StepFun Pricing", url: "https://platform.stepfun.ai/docs/en/guides/pricing/details", type: "pricing" },
      { label: "Artificial Analysis StepFun", url: "https://artificialanalysis.ai/text-to-speech/model-families/stepfun", type: "benchmark" },
      { label: "StepFun Audio Models", url: "https://platform.stepfun.ai/docs/en/guides/models/audio", type: "docs" },
    ],
  },
];

export function getTTSData(): TTSData[] {
  return ttsDatabase;
}

export function getTTSById(id: string): TTSData | undefined {
  return ttsDatabase.find((t) => t.id === id);
}

export function getTTSByCategory(category: TTSCategory): TTSData[] {
  return ttsDatabase.filter((t) => t.category === category);
}
